### ISSUE TITLE
Control ability to register with a pattern, e.g. to enable registration only for users from one organisation

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#1006]
On sites like Insights we might like to allow users to register if they have a particular organisational email account, e.g. sarah.smith@highland.gov.uk but not if they aren't from highland.gov.uk

We can achieve this with a new administrative config setting: "Registration email pattern", this being a regular expression defining the test.

This check would then be implemented in client-side and server-side validation on the registration form. Suitable default feedback for a validation failure (which should come from a resx) can actually be the same as we already have: "The email address does not appear to be valid". (That's what you see already if you enter a bad email, and we should not leak more information - a customer would normally include more information about registration in the configurable text above the registration form).

This would typically be used in combination with "Require confirmed email"=True as without that a user could sniff the page for the pattern and get in.

**Comment by JimKerslake** [comment]
@CrispinF 
It would reduce the complexity a bit (maybe quite a lot) if we had a new config property called something like "Registration email domains" which allowed input of a CSV string via the UI, something like this:

idoxgroup.com,esdm.co.uk,highland.gov.uk

(As opposed to the end user entering a Regex...)

And then we would assume that all we ever want to do with this property is validate registrations by the domain part of the email.

We could then potentially not have to deal with regex patterns (and ensuing character escaping bugs) at all...  and the end user has a better chance of getting it right...

but the question then is whether that is sufficient flexibility in the intended use of this property?   Any credible use cases we can think of where we would want more flexibility than this?  
(I suppose if we used regexes we could use negative patterns... allow anybody except certain dodgy domains...)

**Comment by CrispinF** [comment]
@JimKerslake that would meet the known use cases, so I'd be happy with that proposal.

**Comment by JimKerslake** [comment]
@markidox  I would start out here by adding a new string property to cloudscribe.Core.Models.SiteSettings model

Then create fresh migrations for all 4 platforms, and hopefully they should pick up the new field (and not any other unwanted junk at the same time)

That should add a new field to cs_Site
(we are of course tenant-specific here - different tenant sites will each have their own specification of this property)

The 5th supported platform (NoDb) ought to pick the property up with no need / concept of migrations.

After that, try modifying the site settings admin UI to save and return this new property for each site.

After that, I'd try implementing the *server* side check on handling new user registration...
Using the csv model above, there is probably some C# helper (a bit like a URLBuilder) that can check that an email address is on one of the correct specified domains (nicer than just string.EndsWith) - and watch out for case sensitivity... I guess we want this check case insensitive.

There's probably already support in the registration code for reporting back reg errors to the UI, though as said above, we deliberately don't return any helpful information for this kind of thing to the UI for security reasons (though we can write things in more detail to the application log).

**Comment by CrispinF** [comment]
And properties should have the work 'permitted' in for clarity, so it's "Registration permitted email domains" (etc).

**Comment by JimKerslake** [comment]
It also isn't as simple as above because sadly one definition of the SiteSettings model doesn't seem to be enough...

Watch out for stuff like this, whatever it is for, in various places:

```
       public static SiteSettings FromISiteSettings(ISiteSettings i)

            SiteSettings s = new SiteSettings
            {
                ConcurrencyStamp           = i.ConcurrencyStamp,
                AccountApprovalEmailCsv    = i.AccountApprovalEmailCsv,
                AddThisDotComUsername      = i.AddThisDotComUsername,
```
Seems to be enumerating all properties on the model to convert it between SiteSettings and ISiteSettings.  (why...?)


Also...
cloudscribe.Core.Models.DataExtensions.ModelDataExtensions
LoadFromReader(this ISiteSettings site, DbDataReader reader)

```
            site.SiteName = reader["SiteName"].ToString();
            site.Theme = reader["Skin"].ToString();
            site.AllowNewRegistration = Convert.ToBoolean(reader["AllowNewRegistration"]);
```

Again we seem to be traversing every property on the model explicitly... for some purpose.
(cloudscribe does that kind of thing a fair bit, to avoid using AutoMapper)

I just found those on brief inspection - there may well be more places where your new property might simply go missing if it isn't explicitly set.

**Comment by markidox** [comment]
@CrispinF This work has now been completed, the Nuget packages are on our Nexus system but have not gone fully live yet.

If you want to take a look/test it to make sure you are happy, you will need to create a new Cloudscribe project from the VS Template, then once you've logged in, gone to Admin>Site Settings and you will see the new field.

If you want to test it, add your domain in there, e.g. idoxgroup.com, logout and attempt to register with an idoxgroup.com email and without.

If you're happy for me to push it live just let me know.

**Comment by CrispinF** [comment]
@JimKerslake could you possibly test this and show me when you've got it active?

**Comment by markidox** [comment]
Live and tested.

**Comment by CrispinF** [comment]
Re-opening with a slight niggle: if a registration fails as it doesn't meet the requirements, the page displays the "Registration Failed" feedback, but the registration pre-amble disappears. E.g.

![image](https://github.com/user-attachments/assets/6d315ae2-f257-4c5a-a194-8a738a7464a3)

whereas for other validation issues, the pre-amble stays showing. This is better as the pre-amble is likely to contain clues for the user as to why the registration has failed, such as "Only employees of Acme Corp. can register for this website".

e.g. in one example site with some preamble:

![image](https://github.com/user-attachments/assets/a76e45d2-acd0-403e-b151-e88595d3dc29)

**Comment by markidox** [comment]
@CrispinF So, I can show the SiteName from the DB in the error message, but this could be anything, i.e. it may not be a company with employees. They are also able to enter multiple TLD's too. Should I say something like "Please use the email address provided by {sitename} or contact the administrator for access."

**Comment by CrispinF** [comment]
@markidox I obviously didn't explain my point very well - the issue is not in the feedback message; the issues is that it is no longer showing the pre-amble.

**Comment by JimKerslake** [comment]
Tested - nuget deployed - closing - jk
