### ISSUE TITLE
Pager on IP addresses list has  broken cosmetics on /useradmin/useractivity?userid=

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#1007]
Looking at a v6 site, a user has lots of IP addresses causing the pager to appear, and it looks like this:

![image](https://github.com/user-attachments/assets/3e67adbd-adea-4dde-a3e1-d338eadbb7c3)

while I think it should have this kind of styling:

![image](https://github.com/user-attachments/assets/8b9b1063-d627-42c7-a7a5-bdd4bc05288a)

Please check this in a v8 site, and either close this if it's already fixed, or fix!

**Comment by StewartBellamy** [comment]
The pager probably still has Bootstrap4 CSS classes.

**Comment by markidox** [comment]
@CrispinF Have updated this in the IP section, however, I've noticed that it doesn't look like any of the pagination calls in the admin area, or very few at least, have styling on them, so will, from what I can see, look like your first image.

Do you want me to update them all with the styling?

<img width="151" alt="pagination" src="https://github.com/user-attachments/assets/681ca94e-e5fb-493c-a272-eea7f9867675">

**Comment by CrispinF** [comment]
@markidox yes please - all pagination should use the same styling unless you find a good reason for exceptions.

**Comment by markidox** [comment]
completed

**Comment by CrispinF** [comment]
@markidox can you specify where else pagination was fixed, as will need to test. Thanks!

**Comment by markidox** [comment]
@CrispinF It was only in two places in the end (the others were older Bootstrap versions). The one you found and Role List in the admin area too
