### ISSUE TITLE
Error: System.TypeLoadException: 'Could not resolve type 'AspNetCoreGeneratedDocument.Views_Account_EmailConfirmationRequired' in assembly 'cloudscribe.Core.CompiledViews.Bootstrap5, Version=8.0.7.0, Culture=neutral, PublicKeyToken=null'.'

### ISSUE THREAD

**Issue by PCAssistSoftware** [cloudscribe/cloudscribe#1019]
Error message when trying to run:

Exception User-Unhandled

System.TypeLoadException: 'Could not resolve type 'AspNetCoreGeneratedDocument.Views_Account_EmailConfirmationRequired' in assembly 'cloudscribe.Core.CompiledViews.Bootstrap5, Version=8.0.7.0, Culture=neutral, PublicKeyToken=null'.'

Call stack:

 	[External Code]	
>	cloudscribe_test2.dll!cloudscribe_test2.Startup.Configure(System.IServiceProvider serviceProvider, Microsoft.AspNetCore.Builder.IApplicationBuilder app, Microsoft.AspNetCore.Hosting.IWebHostEnvironment env, Microsoft.Extensions.Logging.ILoggerFactory loggerFactory, Microsoft.Extensions.Options.IOptions<cloudscribe.Core.Models.MultiTenantOptions> multiTenantOptionsAccessor, Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Builder.RequestLocalizationOptions> localizationOptionsAccessor) Line 160	C#
 	[External Code]	
 	cloudscribe_test2.dll!cloudscribe_test2.Program.Main(string[] args) Line 39	C#

Can recreate by doing following:

Create project using template in Visual Studio 2022

![image](https://github.com/user-attachments/assets/4af872d6-b0b1-45c2-9d94-0134e100961b)

Same problem occurs if I select "use a single tenant/site"

Build and run the project in Visual Studio, starts to load and then error as below

![image](https://github.com/user-attachments/assets/6187797f-000c-4700-a526-da2f8dcc46d6)

**Comment by PCAssistSoftware** [comment]
If I click continue in Visual studio a few times then a browser window shows the below:

An error occurred while starting the application.
TypeLoadException: Could not resolve type 'AspNetCoreGeneratedDocument.Views_Account_EmailConfirmationRequired' in assembly 'cloudscribe.Core.CompiledViews.Bootstrap5, Version=8.0.7.0, Culture=neutral, PublicKeyToken=null'.
System.Reflection.TypeNameParser.GetTypeFromDefaultAssemblies(string typeName, ReadOnlySpan<string> nestedTypeNames)

TypeLoadException: Could not resolve type 'AspNetCoreGeneratedDocument.Views_Account_EmailConfirmationRequired' in assembly 'cloudscribe.Core.CompiledViews.Bootstrap5, Version=8.0.7.0, Culture=neutral, PublicKeyToken=null'.
System.Reflection.TypeNameParser.GetTypeFromDefaultAssemblies(string typeName, ReadOnlySpan<string> nestedTypeNames)
System.Reflection.TypeNameParser.GetType(string typeName, ReadOnlySpan<string> nestedTypeNames, string assemblyNameIfAny)
System.Reflection.TypeNameParser.Parse()
System.Reflection.TypeNameParser.GetTypeHelper(Char* pTypeName, RuntimeAssembly requestingAssembly, bool throwOnError, bool requireAssemblyQualifiedName)
System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
System.Reflection.CustomAttribute.AddCustomAttributes(ref ListBuilder<object> attributes, RuntimeModule decoratedModule, int decoratedMetadataToken, RuntimeType attributeFilterType, bool mustBeInheritable, ListBuilder<object> derivedAttributes)
System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, int decoratedMetadataToken, int pcaCount, RuntimeType attributeFilterType)
System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, bool inherit)
System.Reflection.CustomAttributeExtensions.GetCustomAttributes<T>(Assembly element)
Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemLoader.LoadItems(Assembly assembly)
Microsoft.AspNetCore.Mvc.ApplicationParts.RazorCompiledItemFeatureProvider.PopulateFeature(IEnumerable<ApplicationPart> parts, ViewsFeature feature)
Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature<TFeature>(TFeature feature)
Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler.EnsureCompiledViews(ILogger logger)
Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompilerProvider..ctor(ApplicationPartManager applicationPartManager, ILoggerFactory loggerFactory)
System.RuntimeMethodHandle.InvokeMethod(object target, Void** arguments, Signature sig, bool isConstructor)
System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(object obj, Span<object> copyOfArgs, BindingFlags invokeAttr)
System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<T>(IServiceProvider provider)
Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action<IRouteBuilder> configureRoutes)
cloudscribe_test2.Startup.Configure(IServiceProvider serviceProvider, IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory, IOptions<MultiTenantOptions> multiTenantOptionsAccessor, IOptions<RequestLocalizationOptions> localizationOptionsAccessor) in Startup.cs
-
            app.UseCloudscribeCore();
#pragma warning disable MVC1005 // Cannot use UseMvc with Endpoint Routing.
            // workaround for 
            //https://github.com/cloudscribe/cloudscribe.SimpleContent/issues/466
            app.UseMvc(routes =>
                       {
                           routes.UseCustomRoutes();
                       });
#pragma warning restore MVC1005 // Cannot use UseMvc with Endpoint Routing.
            //             app.UseEndpoints(endpoints =>
System.RuntimeMethodHandle.InvokeMethod(object target, Void** arguments, Signature sig, bool isConstructor)
System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)
Microsoft.WebTools.BrowserLink.Net.HostingStartup+<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Watch.BrowserRefresh.HostingStartup+<>c__DisplayClass1_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.WebTools.ApiEndpointDiscovery.HostingStartup+<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
Microsoft.Extensions.Hosting.Internal.Host.ForeachService<T>(IEnumerable<T> services, CancellationToken token, bool concurrent, bool abortOnFirstException, List<Exception> exceptions, Func<T, CancellationToken, Task> operation)
Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
cloudscribe_test2.Program.Main(string[] args) in Program.cs
-
            }
            var env = host.Services.GetRequiredService<IWebHostEnvironment>();
            var loggerFactory = host.Services.GetRequiredService<ILoggerFactory>();
            ConfigureLogging(env, loggerFactory, host.Services, config);
            host.Run();
        }
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {

Show raw exception details
.NET 8.0.8 X64 v8.0.0.0    |   Microsoft.AspNetCore.Hosting version 8.0.8+954f61dd38b33caa2b736c73530bd5a294174437    |    Microsoft Windows 10.0.22621    |   [Need help?](http://go.microsoft.com/fwlink/?LinkId=517394)

**Comment by markidox** [comment]
Thanks @PCAssistSoftware We have managed to recreate the issue and are looking into it now.

**Comment by PCAssistSoftware** [comment]
> Thanks @PCAssistSoftware We have managed to recreate the issue and are looking into it now.

Excellent, thank you

**Comment by markidox** [comment]
@PCAssistSoftware Update for you: we believe we have resolved the issue and are in the process of completing further testing with the aim of releasing a fix tomorrow (12/09). Will update you once that has been released.

**Comment by PCAssistSoftware** [comment]
Brilliant, thanks for looking at it so quickly, will test it as soon as released!

**Comment by markidox** [comment]
@PCAssistSoftware Updates have been released to resolve this issue. I'll close this ticket but if you have any issues with the release please feel free to reopen it.

**Comment by PCAssistSoftware** [comment]
@markidox - many thanks, appears to be working fine now
