### ISSUE TITLE
"Failed Logins" not working

### ISSUE THREAD

**Issue by PCAssistSoftware** [cloudscribe/cloudscribe#1023]
Purposefully tried login in with wrong password multiple times on both admin account and a normal user account and "failed logins" still shows as 0.

Tried with NoDB and SQLite - same problem

**Comment by CrispinF** [comment]
This is working for me in cloudscribe.com
![image](https://github.com/user-attachments/assets/8e9f92aa-d7a0-45f8-8926-524fec7f2d6b)

@PCAssistSoftware I wonder if you are aware that the count is reset to zero on successful login? So if you are testing this with the same account that you then use to check the count, it will always show zero!
Could you try with a different user account, and check the counter immediately after a failed attempt?

**Comment by PCAssistSoftware** [comment]
Thanks, and no I wasn’t aware the count is reset to zero as not found any documentation on it.  Can confirm it is working by trying twice as user and then logging in as admin to check figures

Darren Rose
PC Assist @ Home<http://www.pcassistonline.co.uk/>
PC Assist Software<http://www.pcassistsoftware.co.uk/>
01508 471459
***@***.******@***.***>

**Comment by CrispinF** [comment]
@PCAssistSoftware thanks for confirming. 
And yes there could be more documentation around some of the basic cloudscribe functionality - mostly we hope it is self-explanatory, but this one clearly is not.
