### ISSUE TITLE
Enable setting password complexity settings in the Administration > Security Settings

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#1025]
At present these are in the database with no UI.

**Comment by markidox** [comment]
@CrispinF Which of these am I surfacing...all?

1. Max invalid password attempts
2. Min required password length
3. Password require digit
4. Password require lowercase
5. Password require non-alpha
6. Password require uppercase

For the latter (3 to 6) are we putting a number on how many of those are required, i.e. 3 digits, 2 lowercase etc, etc, or just that a minimum of one is required?

**Comment by CrispinF** [comment]
@markidox yes, all, in a section of the page for "Password settings".
Look at the existing database and implementation, but I believe they are all integers. I think we should put some validation on though, as some settings could be absurd.
E.g. Max invalid password attempts cannot be <1, unless we make it that zero equates to "there is no limit" - study the existing implementation.
Min required password length - I don't think we should permit less than 7.
The others must 0 or more, integers. Do check, but I believe the implementation is that these are the minimum number of this thing that must be present for a new/changed password. I might be wrong - they could be simply 0/1?
The labelling will need to be much clear than these strings!

**Comment by markidox** [comment]
@JimKerslake Easy one to test. [PR is here](https://github.com/cloudscribe/cloudscribe/pull/1027). 
The packages are up on Nexus (core.web and compiledviews.bootstrap5), both 8.0.11, just need to create a new project from the template, go to security settings and you should see the password settings section to play with.
