### ISSUE TITLE
Potential bug: auto-timeout function not working

### ISSUE THREAD

**Issue by LaineS** [cloudscribe/cloudscribe#1035]
I noticed in the recent .net 8 updates that the auto-timeout function is not working (i.e. doesn't ever seem to fire). I also noticed a JS error onload:

![image](https://github.com/user-attachments/assets/0bec35f0-755e-4346-a83c-e3e377ab5372)

![image](https://github.com/user-attachments/assets/02324031-97d3-4146-9068-63ad92768b29)

**Comment by JimKerslake** [comment]
I see that JS error too - but oddly enough it doesn't prevent the timeout popup window working for me in a fresh net8 template site.

I assume you've made sure that you do have the partial view for the popup in your _layout file?
```
    <main id="content" class="col order-3">
        <partial name="AlertsPartial" />
        <partial name="_CookieConsentPartial" />
        **<partial name="_AutoLogoutWarningPartial" />**
        @RenderBody()
    </main>
```
Will fix that JS glitch anyway, and then maybe try again...

**Comment by JimKerslake** [comment]
@LaineS  tested and again confirmed that this works out of the box in a new cs template site (MSSQL) BUT a couple of things to remember in testing: 

After having set the inactive session expiry time via the UI (as it is now done) it's a good idea to recycle the app pool to prompt a reloading of the site security settings (or if running locally just re-build), for it to take effect

If testing with an existing logged-in user, that user then needs to logout and back in, so they obtain a new auth cookie with the session expiry time in it (which gets read from the revised site security settings)

The second of those I seem to forget every time.

![image](https://github.com/user-attachments/assets/971a1fab-8004-45a7-a014-1528d3cb913d)


I'll fix that JS error anyway - slightly mystified how things are working with that error in place.

**Comment by JimKerslake** [comment]
cloudscribe.Web.StaticFiles   v 8.0.6

Above JS error was in 'belt and braces' defensive code seldom likely to be hit
