### ISSUE TITLE
It could be useful to have a "send test mail" button.

### ISSUE THREAD

**Issue by paulvanbladel** [cloudscribe/cloudscribe#379]
When configuring an email address in the security config, it could be useful to be able the correct functioning of the configured email.

**Comment by joeaudette** [comment]
good idea!

**Comment by joeaudette** [comment]
I wonder if you would have time to implement an email test form on the email settings page? Shouldn’t take a lot of effort but I am swamped right now, a pull request would be welcome since you already have a contributor agreement on file.

**Comment by paulvanbladel** [comment]
Sure. I will give it a try.

**Comment by joeaudette** [comment]
I have implemented this, it will be in updated nugets soon.

**Comment by joeaudette** [comment]
just published update dnugets
