### ISSUE TITLE
New Project From Visual Studio Template Won't Create Initial Admin User

### ISSUE THREAD

**Issue by jsalehy** [cloudscribe/cloudscribe#394]
When using the latest Visual Studio project template to create a barebones project with SQL Server storage, the following exception is thrown when it attempts to insert the initial admin user, shortcutting the rest of the initial set up process.

`System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'NormalizedUserName', table 'TestApp.dbo.cs_User'; column does not allow nulls. INSERT fails.`

Steps to reproduce:

1. Create a new project using the cloudscribe Web Application project template
2. See the image below for installed options

![screen shot 2018-04-25 at 3 19 27 pm](https://user-images.githubusercontent.com/4038166/39271056-7e691024-489d-11e8-9985-a1d2c521e758.png)

3. Change the EntityFrameworkConnection value in appsettings.json to a valid connection string
4. Build and start the project (no other changes were made)

Additional information:

SQL Profiler was used to look at the offending query:

`exec sp_executesql N'SET NOCOUNT ON;
INSERT INTO [cs_User] ([Id], [AccessFailedCount], [AccountApproved], [AgreementAcceptedUtc], [AuthorBio], [AvatarUrl], [CanAutoLockout], [Comment], [CreatedUtc], [DateOfBirth], [DisplayInMemberList], [DisplayName], [Email], [EmailConfirmSentUtc], [EmailConfirmed], [FirstName], [Gender], [IsDeleted], [IsLockedOut], [LastLoginUtc], [LastModifiedUtc], [LastName], [LastPasswordChangeUtc], [LockoutEndDateUtc], [MustChangePwd], [NewEmail], [NewEmailApproved], [NormalizedEmail], [NormalizedUserName], [PasswordHash], [PhoneNumber], [PhoneNumberConfirmed], [RolesChanged], [SecurityStamp], [Signature], [SiteId], [TimeZoneId], [Trusted], [TwoFactorEnabled], [UserName], [WebSiteUrl])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19, @p20, @p21, @p22, @p23, @p24, @p25, @p26, @p27, @p28, @p29, @p30, @p31, @p32, @p33, @p34, @p35, @p36, @p37, @p38, @p39, @p40);
',N'@p0 uniqueidentifier,@p1 int,@p2 bit,@p3 datetime2(7),@p4 nvarchar(4000),@p5 nvarchar(255),@p6 bit,@p7 nvarchar(4000),@p8 datetime2(7),@p9 datetime2(7),@p10 bit,@p11 nvarchar(100),@p12 nvarchar(100),@p13 datetime2(7),@p14 bit,@p15 nvarchar(100),@p16 nvarchar(4000),@p17 bit,@p18 bit,@p19 datetime2(7),@p20 datetime2(7),@p21 nvarchar(100),@p22 datetime2(7),@p23 datetime2(7),@p24 bit,@p25 nvarchar(100),@p26 bit,@p27 nvarchar(100),@p28 nvarchar(50),@p29 nvarchar(4000),@p30 nvarchar(50),@p31 bit,@p32 bit,@p33 nvarchar(50),@p34 nvarchar(4000),@p35 uniqueidentifier,@p36 nvarchar(50),@p37 bit,@p38 bit,@p39 nvarchar(50),@p40 nvarchar(100)',@p0='C6CE1CAA-8F5D-430C-A968-CB84DF88D999',@p1=0,@p2=1,@p3=NULL,@p4=NULL,@p5=NULL,@p6=0,@p7=NULL,@p8='2018-04-25 20:22:10.2562135',@p9=NULL,@p10=1,@p11=N'Admin',@p12=N'admin@admin.com',@p13=NULL,@p14=1,@p15=NULL,@p16=NULL,@p17=0,@p18=0,@p19=NULL,@p20='2018-04-25 20:22:10.2562138',@p21=NULL,@p22=NULL,@p23=NULL,@p24=0,@p25=NULL,@p26=0,@p27=N'ADMIN@ADMIN.COM',@p28=NULL,@p29=N'admin||0',@p30=NULL,@p31=0,@p32=0,@p33=NULL,@p34=NULL,@p35='76C1FE19-38A0-4B17-9A89-7F31F5C0813C',@p36=NULL,@p37=0,@p38=0,@p39=N'admin',@p40=NULL`

**Comment by joeaudette** [comment]
@jsalehy Thanks a lot for the bug report! I just figured out it was a recent change that caused this. I've just published updated nugets that should solve it. Might take up to an hour for the new nugets to get indexed and be available but after that can you test again and confirm you agree it is fixed.

**Comment by jsalehy** [comment]
No problem. Thanks Joe!

**Comment by jsalehy** [comment]
@joeaudette take a look at SiteManager.CreateAdminUser... the UserName is changed after the call to BuildInitialAdmin, so normalization might need to happen again.

**Comment by jsalehy** [comment]
@joeaudette I just re-tested and all looks good.

**Comment by joeaudette** [comment]
Thanks @jsalehy! I will add the normalization logic there in SiteManager but that one isn't really causing any error or problem so no urgency to ship a nuget on that one.

When users are created or updated via the Identity SiteUserManager the normalized strings get handled correctly, its just the initial  site admin user is not created that way but is seeded directly into the data layer. I recently removed a default value of "" for that property on SiteUser and that is what caused the null error going into the db for the initial user. Previously "" was going in not a normalized string, but since we use email for login by default the normalized user name doesn't come into play for new setups, and assuming the user changes the admin user name before deployment then that would get sorted by UserManager. Still good to make sure those get valid initial values, so will fix that.
