### ISSUE TITLE
Incorrect IP address for page not found in system log.

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe#432]
I found that on my site that I deployed in internet all 404 entries in System Log have ip address 127.0.0.1.
It looks like like this:
` 6/24/2018 12:04:35 PM Warning 127.0.0.1 cloudscribe.Core.Web.Controllers.Mvc.OopsController /oops/error/404
handled 404 for url: /xsomepagex from ipaddress 127.0.0.1 `

Not a big problem, just from my past experience sometimes some nasty guy from particular ip address testing some crawler or similar stuff and having thousands requests per minute and it is easy to bad him by ip address.

**Comment by joeaudette** [comment]
yeah, I'm seeing that too, I wonder if something changed over different versions of aspnet core.
You can see in [the code here](https://github.com/cloudscribe/cloudscribe.Logging/blob/master/src/cloudscribe.Logging.Web/WebRequestInfoProvider.cs) that I'm trying to get the remote address:

    return connection.RemoteIpAddress.ToString();

but the way kestrel runs behind IIS like a proxy server, it seems we are just getting the loopback address of the server.

I just changed the code and pushed new nugets for logging to try to check x-forwarded header as in this [answer on stackoverlfow](https://stackoverflow.com/questions/28664686/how-do-i-get-client-ip-address-in-asp-net-core)

**Comment by cheverdyukv** [comment]
I checked for updated packages, updated cloudscribe logging and couple other but still ip address the  same
`    <PackageReference Include="cloudscribe.Core.Web" Version="3.0.7" />
    <PackageReference Include="cloudscribe.Core.CompiledViews.Bootstrap4" Version="3.0.5" />
    <PackageReference Include="cloudscribe.Core.Storage.NoDb" Version="3.0.2" />
    
    <PackageReference Include="cloudscribe.Core.SimpleContent" Version="3.0.2" />
    <PackageReference Include="cloudscribe.SimpleContent.Web" Version="3.0.5" />
    <PackageReference Include="cloudscribe.Core.SimpleContent.CompiledViews.Bootstrap4" Version="3.0.3" />
    <PackageReference Include="cloudscribe.SimpleContent.CompiledViews.Bootstrap4" Version="3.0.2" />
    <PackageReference Include="cloudscribe.SimpleContent.MetaWeblog" Version="3.0.1" />
    <PackageReference Include="cloudscribe.SimpleContent.Syndication" Version="3.0.1" />
    <PackageReference Include="cloudscribe.SimpleContent.Storage.NoDb" Version="3.0.2" />

    <PackageReference Include="cloudscribe.Logging.Web" Version="3.0.6" />
    <PackageReference Include="cloudscribe.Logging.NoDb" Version="3.0.2" />
`

**Comment by joeaudette** [comment]
I think this may shed some light on the issue, maybe you could experiment with the suggestions there?

https://stackoverflow.com/questions/43749236/net-core-x-forwarded-proto-not-working

or more specifically try changing like this in RoutingAndMvc.cs

            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
                options.KnownNetworks.Clear();
                options.KnownProxies.Clear();
            });

and let me know if that solves it. I'm working on other things at the moment and can't get to trying it for a little while

**Comment by cheverdyukv** [comment]
Hi Joe.

This is by all means low priority. So I can wait as long as it takes.
I did try 
`            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders = HttpOverrides.ForwardedHeaders.XForwardedFor | HttpOverrides.ForwardedHeaders.XForwardedProto;
                options.KnownNetworks.Clear();
                options.KnownProxies.Clear();
            });`
but now instead of page not found I got connection reset and nothing in log.

**Comment by joeaudette** [comment]
I found the problem.
Things changed in how forwarded headers are setup. If you are hosted in IIS you don't need to do anything, the IIS hosting module will set up forwarded headers correctly.

So the solution is remove this from Startup.cs:

    app.UseForwardedHeaders();

and remove this from /Config/RoutingAndMvc.cs

        services.Configure<ForwardedHeadersOptions>(options =>
        {
            options.ForwardedHeaders = Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedProto;
        });

after doing that I find my log in production now shows correct ip address, and user ip addresses are tracked correctly again.

Please close this after you verify.

**Comment by joeaudette** [comment]
I have updated the cloudscribe project template to remove those.

**Comment by cheverdyukv** [comment]
It work!
