### ISSUE TITLE
cloudscribe.Web.Common is too big

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe#434]
Hi

It is not that big deal and definitely not urgent. 
I just found out that during uploads the last file is always cloudscribe.Web.Common.dll. It is more that 11Mb and more than 30% of total deploy size. 

I found that resources of that dlls (fonts, js, css) are about 11,452,001 bytes. I used small hosting in Europe and it takes quite some time to upload. And it is recompiled often so I have to upload it. 

Then I found that it is contains normal and minified version of js. For example:
jquery.js and jquery.min.js
jquery-ui.js and jquery-ui.min.js
etc
and non minified versions are quite big. 

Also I believe that that assembly takes it size in memory (11Mb) and for small hosting it could be critical. Usually these hosters allow 200Mb of RAM and if you go over that limit they recycle your app.

Perhaps better to split these kind of resources because they do not change that often?

**Comment by joeaudette** [comment]
I've moved the static files to a separate library and documented the easy to fix breaking change here:

https://github.com/cloudscribe/Announcements/issues/6

**Comment by cheverdyukv** [comment]
Thank you. I will review it soon.

**Comment by cheverdyukv** [comment]
Works great as usual! Thank you,
