### ISSUE TITLE
Avatar and Username on seperate lines in hamburger menu

### ISSUE THREAD

**Issue by AlexHorridge-ESDM** [cloudscribe/cloudscribe#437]
Currently the [hamburger menu/Main nav](https://github.com/cloudscribe/cloudscribe/blob/master/src/cloudscribe.Core.CompiledViews.Bootstrap4/Views/Shared/_LoginPartial.cshtml) has the avatar and username in separate list items, resulting in 2 lines:

![image](https://user-images.githubusercontent.com/33840501/42327215-257c4bd6-8063-11e8-900f-2cd47adb7680.png)

This would be more appropriate as one line.

**Comment by joeaudette** [comment]
Thanks for the bug report!

I've published updated nugets for the compiled views that will hide the avatar list item on all but large screens so it won't be in the responsive hamburger menu.

It may take a little while for the new nugets to be indexed and available.
