### ISSUE TITLE
Unable to find the "js" and cr folders

### ISSUE THREAD

**Issue by dreamerNcoder** [cloudscribe/cloudscribe#460]
Hi, 

I cloned this project and wanted to play around, but I was not able to make it works :( 
As below scripts are not found.

Any chance the below js and cr folder  missed to commit ?
 <environment names="Development">
        <script src="~/js/jquery.js"></script>
        <script src="~/js/bootstrap4.bundle.js"></script>
        <script src="~/cr/js/bs4.smartmenus.min.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/jquery.min.js"></script>
        <script src="~/js/bootstrap4.bundle.min.js"></script>
        <script src="~/cr/js/bs4.smartmenus.min.js"></script>
    </environment>

**Comment by joeaudette** [comment]
Can you login and change the theme to custom1 and let me know if that solves it? I think it may use the wrong theme by default which I can change so others don't run into this if that solves it. In my local copy I'm using custom1 theme.

**Comment by joeaudette** [comment]
I just changed the default theme to custom1 and pushed changes but that will only affect new databases, you should login and change yours to custom1

**Comment by dreamerNcoder** [comment]
Thanks, 
This is awesome, I was looking for something like this.
 
I selected bootstrap4, as custom1 didnt work for me. 

I can see now when I try with Tenant1SpaPlymer sample, I am not able to login, it just give error page with not info.
![image](https://user-images.githubusercontent.com/12616063/44224337-bc908b80-a1a7-11e8-9c90-08ed801c6b48.png)

**Comment by joeaudette** [comment]
you have to understand this is my development environment, it isn't a demo, that is just for my own tests and it won't work for you with different data than what I have and what I configured those test aps. You would have to create clients and set the right client ids and setup apis etc.

If you want a working demo for idserver see here:
https://github.com/cloudscribe/sample-idserver

It uses NoDb so it is prepopulated with data and you would have the same data so it should work for you the same as me.

**Comment by joeaudette** [comment]
really I don't recommend working with the source solution unless you just want to learn or if you were trying to solve a bug.
I recommend use only our nuget packages and use our project template to wire up the packages you want:
https://marketplace.visualstudio.com/items?itemName=joeaudette.cloudscribeProjectTemplate

**Comment by dreamerNcoder** [comment]
Yes, I was already using the https://marketplace.visualstudio.com/items?itemName=joeaudette.cloudscribeProjectTemplate

But wanted to look into the code so just set up this.

 Thanks, 

Great job,

**Comment by joeaudette** [comment]
Thanks!

**Comment by dreamerNcoder** [comment]
Yes, Thanks, 
I was not having gulp, had to install npm -g gulp to make the task run.
