### ISSUE TITLE
failed to resolve url for node DeletePersonalData

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe#481]
Hi

I'm not sure if this is right area to ask but I have a lot of errors in System log:

failed to resolve url for node DeletePersonalData
failed to resolve url for node PersonalData

for each site

**Comment by joeaudette** [comment]
are you up to date on all the cloudscribe nugets?
Those are relatively new menu items added to help with GDPR. If you don't have all the nugets updated you may be missing those controller actions and that would cause the errors.

**Comment by cheverdyukv** [comment]
Hi Joe

I thought I'm behind and yesterday I updated to latest and problem is still there.

**Comment by joeaudette** [comment]
I'm not able to reproduce the problem. I suggest clear the log and double check your versions.

**Comment by cheverdyukv** [comment]
I checked in VS and no new version of packages available. And I did clean log and access site/api/sitemap and instantly got more errors in system log.

**Comment by joeaudette** [comment]
please make a screen shot of your versions under Administration > System Information and post it here

**Comment by joeaudette** [comment]
or post your .csproj file contents

**Comment by cheverdyukv** [comment]
Server is in Europe:
![image](https://user-images.githubusercontent.com/18220536/44928398-a38deb80-ad0c-11e8-8e0a-0c325f462b9b.png)

**Comment by joeaudette** [comment]
and your navigation.xml has this?

    <NavNode key="PersonalData"
                controller="Manage"
                action="PersonalData"
                text="Personal Data"
                componentVisibility="child-dropdown,breadcrumbs"
                hideFromAnonymous="true">
              <Children>
              <NavNode key="DeletePersonalData"
                controller="Manage"
                action="DeletePersonalData"
                text="Delete Data"
                componentVisibility="breadcrumbs"
                hideFromAnonymous="true">
                <Children />
                </NavNode>
              </Children>
            </NavNode>
            
          </Children>
        </NavNode>

**Comment by cheverdyukv** [comment]
Yes I did synchronize from new project template few days ago

**Comment by joeaudette** [comment]
do you have any custom routes that could interfere with resolving the url by controller and action?

I would double check your navigation.xml to make sure no typos anywhere. As I said I cannot reproduce the issue.

**Comment by joeaudette** [comment]
ok, there is a little bug, the xml needs to be changed since those nodes should not be in the site map  

    <NavNode key="PersonalData"
                controller="Manage"
                action="PersonalData"
                text="Personal Data"
                componentVisibility="child-dropdown,breadcrumbs"
                excludeFromSearchSiteMap="true"
                hideFromAnonymous="true">
              <Children>
              <NavNode key="DeletePersonalData"
                controller="Manage"
                action="DeletePersonalData"
                text="Delete Data"
                componentVisibility="breadcrumbs"
                excludeFromSearchSiteMap="true"
                hideFromAnonymous="true">
                <Children />
                </NavNode>
              </Children>
            </NavNode>
            
          </Children>
        </NavNode>

notice: excludeFromSearchSiteMap

Though I'm not sure why it would fail to resolve it, that is strange.

**Comment by joeaudette** [comment]
I've fixed that in the templates and published again

**Comment by cheverdyukv** [comment]
Problem gone! Thank you!
