### ISSUE TITLE
Consider enabling sourceLink for the cloudscribe nuget packages

### ISSUE THREAD

**Issue by paulvanbladel** [cloudscribe/cloudscribe#489]
Can increase the cloudscribe quality because devs can simply step into the code when necessary.
See 

- https://www.meziantou.net/2018/07/09/how-to-debug-nuget-packages-using-sourcelink

- https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx

**Comment by joeaudette** [comment]
I have added the source link meta data into the .csproj files and shipped new nugets packaged from the updated .csproj files, so source link should work now.

I think you still have to add this dependency into your own project for it to work:

    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0-beta-63127-02" PrivateAssets="All"/>
