### ISSUE TITLE
conflicts with the imported type 'Views__ViewImports' in 'cloudscribe.Web.Common.Views, Version=3.0.14.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by akdurmus** [cloudscribe/cloudscribe#499]
This package cloudscribe.Web.Common really helps me to prepare emails by using razor views and parse the content. However, I get a little warning as I put in the title. As my project already has a ViewImports.cshtml and the package is installed in class lib.

Is this something that can be avoided?

**Comment by joeaudette** [comment]
You can suppress those warnings by adding this in your .csproj file

      <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <NoWarn>1701;1702;0436</NoWarn>
      </PropertyGroup>
      <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <NoWarn>1701;1702;0436</NoWarn>
      </PropertyGroup>

We suppress those in web apps generated using out project template.
