### ISSUE TITLE
SiteSettings page hangs on first click of Save button - workaround included

### ISSUE THREAD

**Issue by mfoitzik** [cloudscribe/cloudscribe#501]
I have a site set up using host names. If the host name field has a value in it and you click the save button (without actually changing anything in the host name field) the Save button changes to 'Wait' and hangs. If you monitor the network in developer tools you will see that there is one GET request to SiteAdmin/hostnameavailable and it just sits there. You can click on the button a second time and it will proceed.

A workaround (jury rig) that worked for me is triggering a blur event on the hostname field after all of the scripts load at the bottom of the SiteInfo.cshtml file as follows:
<script type="text/javascript">
        $(function () {
            $("#HostName").trigger("blur");
        });        
</script>

**Comment by joeaudette** [comment]
Thanks for the bug report.

I've removed the client side remote validation for host name since it was causing the issue and it looks like I removed it previously from folder name for the same reason. I think server side validation is sufficient for that.

I've published updated nugets.
