### ISSUE TITLE
Cookies consent look bad on iPhone

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe#530]
It looks like that:
https://www.mirabulus.com/
![image](https://user-images.githubusercontent.com/18220536/50405620-8e7e1200-076c-11e9-8f2f-930e3aa6216a.png)
Blogs it is name of the page

**Comment by joeaudette** [comment]
This is easy to fix, I will fix it in the next template release.

To fix it in your copy look in _CookieConsentPartial.cshtml file, on the bottom div class, change float-left to float-lg-left.

**Comment by cheverdyukv** [comment]
Thank you, it did the trick. Should I close this ticket or should I leave it as reminder to fix template?

**Comment by joeaudette** [comment]
This is fixed in the latest template so closing
