### ISSUE TITLE
Failed to determine the https port for redirect in System log

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe#531]
I enabled SSL on my site and everything works great. There is auto redirect and from user standpoint everything works fine. But I see "Failed to determine the https port for redirect" messages in System log. This message came from "Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware /". I checked https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio and it "Port configuration" section I found this: 
A port must be available for the middleware to redirect an insecure request to HTTPS. If no port is available:

    Redirection to HTTPS doesn't occur.
    The middleware logs the warning "Failed to determine the https port for redirect."

I don't really know what to do to fix this. Any ideas?

**Comment by joeaudette** [comment]
This was apparently a change in asp.net core 2.1 https://github.com/aspnet/Announcements/issues/301

Now [they say](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#options) you need to configure the https port

      if(!_environment.IsDevelopment())
            {
                services.AddHttpsRedirection(options =>
                {
                    options.RedirectStatusCode = StatusCodes.Status307TemporaryRedirect;
                    options.HttpsPort = 443;
                });
            }

it might be best to make an appsetting for the port 

     if(!_environment.IsDevelopment())
            {
                var httpsPort = _configuration.GetValue<int>("AppSettings:HttpsPort");
                services.AddHttpsRedirection(options =>
                {
                    options.RedirectStatusCode = StatusCodes.Status307TemporaryRedirect;
                    options.HttpsPort = httpsPort;
                });
            }

**Comment by joeaudette** [comment]
I would put it in Startup.cs right after services.SetupMvc, but I don't think it is important where

**Comment by cheverdyukv** [comment]
I think it fixed it as I don't see these errors anymore. It is a bit strange that we have to specify
