### ISSUE TITLE
What is Google Analytics ProfileId?

### ISSUE THREAD

**Issue by cheverdyukv** [cloudscribe/cloudscribe#532]
Is it what specified here: https://kb.paessler.com/en/topic/35363-where-do-i-find-my-google-analytics-profile-id

I was used to use Tracking ID and a bit confused.

**Comment by joeaudette** [comment]
It is tracking id, I think they used to call it profile id. I will update the label for the next release.

**Comment by cheverdyukv** [comment]
Thanks, changed to tracking Id and now analytics working!
