### ISSUE TITLE
Shared cookie consent question in shared sites mode... and an error changing the setting

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#561]
Not sure whether this is a bug or I've set something up wrong. 
I have a site and child site in related sites mode, set up from VC template. As far as I recall, I didn't change any cookie settings. When I visit the parent in a clean browser I get no cookie consent prompt, but when I visit the child site I do get the consent prompt. This makes sense when I review my site settings... the child site has this:
![image](https://user-images.githubusercontent.com/10574730/52567209-a46e9180-2e03-11e9-8e5a-77f474c3f631.png)
and for the parent site it is switched off.  Pretty sure I didn't set that, but maybe. 
But when I try to change it, and switch this on, I get a "Bad Request" error but with no error in the log.
Ah, and then I get the same error when I try to clear the log.
Yet I can make other changes in site settings without an error.

**Comment by joeaudette** [comment]
Is this bad request happening on localhost with Chrome? If so that happens to me a lot and seems to be  some obscure issue with chrome and the antiforgery cookie not getting validated thus causing bad request with nothing logged. Clearing browser cache and rebooting the machine solves it but somehow clearing site data from the application tab of dev tools doesn't fully solve it though it logs me out, the issue comes back,

Try a different browser and it works fine for me.

**Comment by CrispinF** [comment]
Yes it's chrome, but running on a server. Will try another browser and report back...

**Comment by joeaudette** [comment]
It may be that logging is filtered and removing filters and logging at lower level may give more clues to the problem. I have not seen this issue in production myself, but get it frequently on localhost lately.

**Comment by CrispinF** [comment]
Quite right Joe, it's a Chrome issue. Works fine in Edge.  No issue!

**Comment by joeaudette** [comment]
to me it seems an issue if it happens in production, telling users try a different browser isn't really a solution, just a partial diagnosis. I will try to dig into the issue on localhost, I assume if I can solve it there then it should not happen in production.

Also curious if your production site is using https or not?

**Comment by CrispinF** [comment]
True. The site is on http at present during construction. It may be because I had already deleted cookies in Chrome developer tools to test the cookie consent thing?

**Comment by CrispinF** [comment]
I can give you an admin login to the site if's like to check it out more?

**Comment by joeaudette** [comment]
I've thought maybe the fact I'm using umatrix in chrome could also be a factor. I'll try disabling that for a while.

I doubt very much that the problem will manifest immediately if I login to your site as admin. When I've seen this it starts all of a sudden after working fine for a while.

Are you using https? that is a potential issue as if not then the cookie configuration might not pass the cookie for insecure requests.

**Comment by joeaudette** [comment]
oh, the fact you are not using https is most likely why I've never had this happen in production, all production sites I have use https. It gives me clues to know that.

**Comment by CrispinF** [comment]
not using https at present (site under construction).  I could switch it to https fairly easily.

**Comment by joeaudette** [comment]
I've thought that the localhost issue could be from going back and forth between different solutions that run as localhost and leftover cookies.

**Comment by joeaudette** [comment]
but since it happens for you in production with no https that gives something to investigate.
