### ISSUE TITLE
Confusing "auto-saved content" sequence

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#565]
Apologies if this is in the wrong repo. I've noticed this a couple of times now... this time I edited the Privacy text and clicked save, and got this warning:
![image](https://user-images.githubusercontent.com/10574730/52847885-53adb000-3105-11e9-8a60-c0f7a9363453.png)
The date/time shows is basically "now", and I only made one edit and saved once. If I click OK to compare content, I see that probably the auto-save happened just a few seconds before my manual save:
![image](https://user-images.githubusercontent.com/10574730/52847978-8b1c5c80-3105-11e9-84a0-a5715b89eb88.png)
The options I am offered are rather confusing:
![image](https://user-images.githubusercontent.com/10574730/52848035-aab38500-3105-11e9-9ef6-a6390f50c0e8.png)
Umm?
The confused user (I'm speaking for a friend of course ;-) will tend to click "OK" on the first prompt (because clicking cancel when you are trying to Save just doesn't feel right), and then to click the green button on the second (again because it's confusing but looks like the positive thing to do)… and this of course will result in them reverting to the previous auto-saved version.
If I've understood this right, probably the user should really click Cancel on the first dialogue, as they are simply wanting to save.  If so, I'd probably want to suggest some different phrasing and making the "positive" action the "just go ahead and save please". 
But … what's the reasoning behind showing this dialogue at all? If it's because we do have this auto-saved function and there's no other way of accessing it (?) would it perhaps instead be possible to access it from a "History" button beside the "Save" button on the form, much as there is for CMS pages in SimpleContent?

**Comment by joeaudette** [comment]
Thanks for the bug report. I just published an updated views nuget that should fix this.

The auto save thing saves in browser storage and there is a convention in our ckeditor config to clear it when you save the form, but the convention requires giving the button an id with the word Save in it like btnSave. The id was missing on the privacy save button so the saved data wasn't getting cleared on submit.

**Comment by CrispinF** [comment]
@joeaudette I'm seeing the same thing on /contentsettings/index when saving the Blog "About Content".

**Comment by joeaudette** [comment]
Probably the same issue in a different view, will check it first thing tomorrow.

**Comment by joeaudette** [comment]
this should be fixed in latest nugets. When we added the ckeditor for about content forgot to add the needed button id.
