### ISSUE TITLE
In File Manager, a way to open file, and copy the URL of a file to clipboard

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#581]
Ability to open file at its URL, and copy that URL to clipboard, would be incredibly useful. Could perhaps be in this part of the UI, as perhaps  "Open" and "Copy URL":
![image](https://user-images.githubusercontent.com/10574730/53304787-47e28c00-3871-11e9-83f1-ceab53e1eac8.png)

**Comment by joeaudette** [comment]
I believe in the case of a pdf the download button would open in a new tab while other files would be treated as attachments.

The relative url is already shown just below the Browse tab, it can be copied from there.

**Comment by CrispinF** [comment]
@joeaudette ok fair enough. I had found in Edge I couldn't select and copy the relative URL, but I can in Chrome.
