### ISSUE TITLE
File manager: file not found if its folder path is same as a CMS folder

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#582]
Just noting this as I ran into it.
I have a folder tenant like mysite.com/writings
My sites are sharing everything they can, with these settings:

    "MultiTenantOptions": {
    "Mode": "FolderName",
    "UseRelatedSitesMode": "true",
    "RelatedSiteId": "7923cab3-fc54-4f03-9341-7daf10b1fd01",
	"RelatedSiteAliasId": "s1",
    "SiteUploadFilesRootFolderName": "siteuploadfiles",
	"DefaultNewUserRoles":"Authenticated Users",
	"UserPerSiteWwwRoot": "true",
	"UserPerSiteThemes": "false",
	"UseSharedThemes": "true",
	"SiteFilesFolderName": "sitefiles",
	"SiteThemesFolderName":"themes",
	"SiteContentFolderName":"wwwroot",
	"SharedThemesFolderName":"SharedThemes",
	"ThemeStaticFilesFolderName":"wwwroot"
  }

I created a folder of files like 
d:\mysite\siteuploadfiles\s1\wwwroot\writings

The File Manager could see this folder, but any images/links to files in this folder wouldn't work as I think their addresses were interpreted as page routes.

I hit this in my first ever folder-tenant site, so it's likely others will. Not sure what best solution is, but perhaps adding a "/files/" segment into the route for anything accessible through File Manager could solve it? (breaking existing links, but this is all quite new so that will be fine). If child folder site was called "files" that might still cause problems, but that is most unlikely and easy to cover in docs.

**Comment by joeaudette** [comment]
Thanks for the bug report! This is now fixed in the latest nugets.
