### ISSUE TITLE
How ensure clients pick up theme changes?

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#589]
Hi @joeaudette just wondering how best to ensure browsers fetch changed resources like site.min.css ?
I've just made changes to a theme, published and deployed, and browsers do not fetch the new files unless I prod them to e.g. CTRL+F5.
My minified css are made via bundleconfig.json during the publish (I think!).

In Firefox I see the request uses old cached version:
![image](https://user-images.githubusercontent.com/10574730/53695531-adc09d80-3db4-11e9-84a2-f176596c8942.png)
request/header info:
![image](https://user-images.githubusercontent.com/10574730/53695537-ccbf2f80-3db4-11e9-90c3-84010cb7be0e.png)

I've not seen anything about this in the cloudscribe theming docs. 
Should we perhaps add asp-append-version="true" to the stylesheet links in _Layout.cshtml ?  OK I just  tried that, and it seems to work well... e.g.
`<link rel="stylesheet" href="~/css/site.min.css" cs-resolve-theme-resource="true" cs-shared-theme="true" cs-tenant="@Tenant" asp-append-version="true" />`
first page load after deployment fetches new files, thereafter they are cached.  Is this how you'd recommend doing it or is any problem with this approach?

**Comment by joeaudette** [comment]
yes, actually in the most recent project template I added asp-append-version="true" for all the theme style sheets but existing projects would need to add that.

**Comment by CrispinF** [comment]
OK, thanks @joeaudette good to know that's the right approach.
