### ISSUE TITLE
Contact form email not sending

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#591]
Hi @joeaudette I know this is a long shot as it's MailKit not your code, but I have a site failing to send email from the cloudscribe contact form, using identical setting to another site on the same certificate. The other site sends the email fine, but the cloudscribe email fails with this error:
02/03/2019 21:11:56 Error 62.197.51.xxxcloudscribe.SimpleContactForm.Components.ContactFormProcessor /contact
error sending contact form notification email: An error occurred while attempting to establish an SSL or TLS connection.&#xD;&#xA;&#xD;&#xA;One possibility is that you are trying to connect to a port which does not support SSL/TLS.&#xD;&#xA;&#xD;&#xA;The other possibility is that the SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:&#xD;&#xA;1. The server is using a self-signed certificate which cannot be verified.&#xD;&#xA;2. The local system is missing a Root or Intermediate certificate needed to verify the server&#x27;s certificate.&#xD;&#xA;3. The certificate presented by the server is expired or invalid.&#xD;&#xA;&#xD;&#xA;See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions. : at MailKit.Net.Smtp.SmtpClient.ConnectAsync(String host, Int32 port, SecureSocketOptions options, Boolean doAsync, CancellationToken cancellationToken)&#xD;&#xA; at cloudscribe.Email.Smtp.SmtpEmailSender.SendEmailAsync(String toEmailCsv, String fromEmail, String subject, String plainTextMessage, String htmlMessage, String replyToEmail, Importance importance, Boolean isTransactional, String fromName, String replyToName, String toAliasCsv, String ccEmailCsv, String ccAliasCsv, String bccEmailCsv, String bccAliasCsv, List`1 attachments, String charsetBodyHtml, String charsetBodyText, String configLookupKey)&#xD;&#xA; at cloudscribe.SimpleContactForm.Components.ContactFormProcessor.Process(ContactFormMessage message)

My settings are
  "SmtpOptions": {
    "Server": "smtp.office365.com",
    "Port": "587",
    "User": "xxxx@xxxx.co.uk",
    "Password": "xxxxxxxx",
    "UseSsl": "true",
    "RequiresAuthentication": "true",
    "DefaultEmailFromAddress": "xxxx@xxxx.co.uk",
    "DefaultEmailFromAlias": ""
  },

As noted, both sites are under the same LetsEncrypt certificate. Any ideas??

**Comment by CrispinF** [comment]
With UseSsl as false we get this error:

> error sending contact form notification email: The SMTP server does not support authentication. : at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)&#xD;&#xA; at cloudscribe.Email.Smtp.SmtpEmailSender.SendEmailAsync(String toEmailCsv, String fromEmail, String subject, String plainTextMessage, String htmlMessage, String replyToEmail, Importance importance, Boolean isTransactional, String fromName, String replyToName, String toAliasCsv, String ccEmailCsv, String ccAliasCsv, String bccEmailCsv, String bccAliasCsv, List`1 attachments, String charsetBodyHtml, String charsetBodyText, String configLookupKey)&#xD;&#xA; at cloudscribe.SimpleContactForm.Components.ContactFormProcessor.Process(ContactFormMessage message)

**Comment by joeaudette** [comment]
If you'd like to share the credentials/settings with my privately, I can try changing code to get it working locally then release an updated nuget once it is working

**Comment by joeaudette** [comment]
Closing this for now as nothing actionable to do to confirm or solve this issue. Feel free to reopen if the problem persists and you are able to provide details to produce the problem.
