### ISSUE TITLE
Support for LDAP/AD Authentication

### ISSUE THREAD

**Issue by joeaudette** [cloudscribe/cloudscribe#595]
For intranet installations and also for some public facing scenarios it would be good to support LDAP Authentication which can also be used for Active Directory as an alternative to AzureAD.

**Comment by joeaudette** [comment]
This is now implemented and updated nugets have been published, and documentation has been created here: https://www.cloudscribe.com/using-ldap-authentication

**Comment by SimonAnnetts** [comment]
linked to #922
