### ISSUE TITLE
support for silent logout (without identityserver logout screen)

### ISSUE THREAD

**Issue by paulvanbladel** [cloudscribe/cloudscribe#599]
As discussed on Gitter: silent logout.
Example implementation:
* https://stackoverflow.com/questions/43259870/identityserver4-redirect-to-mvc-client-after-logout
* logout actions in https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/master/Quickstart/Account/AccountController.cs

**Comment by joeaudette** [comment]
fixed in the latest nugets, Thanks!
