### ISSUE TITLE
Suggested update to default cloudscribe-ckeditor-config.js to stop it removing empty <span> and <i> tags

### ISSUE THREAD

**Issue by hsankala** [cloudscribe/cloudscribe#601]
I've been using font-awesome icon in my markup through the source view editor in CKeditor and it keeps removing the empty `<i>` and `<span>` tags.  Googled it and found this [stackoverflow.com - 'ckeditor-strips-i-tag'](https://stackoverflow.com/questions/18250404/ckeditor-strips-i-tag) question/answers.

I override the default with custom CKeditor file (based on the original cloudscribe-ckeditor-config.js ). And added the suggested answer config

 config.protectedSource.push(/<i[^>]*><\/i>/g);
 config.protectedSource.push(/<span[^>]*><\/span>/g);

And it did the trick.  Just a suggested additional to the source cloudscribe-ckeditor-config.js file.

**Comment by joeaudette** [comment]
@hsankala thanks for the tip, I had tried to find a solution for that long ago without luck!

I tried to add code like the answer but then got an error trying to minify the file even trying more than one minifier. So I went with the other answer:

    config.allowedContent = true;
    config.extraAllowedContent = 'p(*)[*]{*};div(*)[*]{*};li(*)[*]{*};ul(*)[*]{*}';
    CKEDITOR.dtd.$removeEmpty.i = 0;

it seems to work and minifies without error.
I've just published an updated cloudscribe.Web.StaticFiles
