### ISSUE TITLE
Hierarchical user management

### ISSUE THREAD

**Issue by varghesep** [cloudscribe/cloudscribe#604]
This is a question only and not an issue.

My app has a hierarchical membership structure. There are **sports clubs** and the **sports clubs** have **members**. The **members** can be admins or just users. 

1. When the admin logs into the application, he should see all the users belong to the club the admin belongs to. 
2. There are hundreds of clubs.
3. When the user registers, he can choose the club. The admin will later approve or deny him.
4. One club should not see the members of a different club.
5. When the user logs in, he will not see any other member in the same club but only his account information.

Can I achieve the above with cloudscribe?

**Comment by joeaudette** [comment]
I'm not sure if cloudscribe can really meet your requirement the way you want it to, but maybe with some customization.

cloudscribe supports multi-tenancy based on either host name or on a first folder segment, but in a given installation currently only one of those approaches can be used. It is an either or config setting that applies to the whole installation so an installation can use either host name tenancy or folder segment tenancy.

In all cases the first site created is the master site/tenant and admins in that site can create new sites/tenants, but child sites cannot create new sites/tenants.
When using  folder tenancy the fist site is still a root level site, it has no special folder segment but new child sites have a first folder segment used in all urls to resolve the tenant.

Your club concept could correlate to a tenant in cloudscribe, but we do not have a single login url for all tenants, each tenant has its own login url. You could implement a custom view that provides a list of tenants/clubs with links to their corresponding login urls.

Each tenant by default has different users, roles, and claims. Only administrators in the master tenant can see and manage users in other tenants. Each non master tenant has its own admin user which can manage only the users and settings for that tenant. Really an admin user is just a user who is a member of the administrators role for the tenant.

Normal users can only see their own personal information, administrative users can see all user data for the tenant.

Hope that helps.
