### ISSUE TITLE
Delete Claim - deleting all of ClaimType

### ISSUE THREAD

**Issue by Externaluse** [cloudscribe/cloudscribe#610]
Users can have multiple claims of the same type, roles are an example. If they're used to finely grain access and one claim is deleted, presently all of the claims of that type are deleted in the Admin.

-- reproduce
- add ClaimType "Access", Value "someModule"
- add ClaimType "Access", Value "otherModule"

Press Delete on "Access someModule". "Access otherModule" will be deleted, too.

**Comment by joeaudette** [comment]
Thanks for the bug report! This is now fixed in the latest nugets.
