### ISSUE TITLE
AuthorizationPolicy must have at least one requirement

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#613]
Using Dynamic Authorisation Policies, I have a Policy that was associated with the Administrators role, but I wanted to remove this.  Did so successfully in /policymanagement/editpolicy?id=4723bf7e-8623-492c-9269-5a414b340c13 but then on loading the component that used my policy it errors with this in the log: "AuthorizationPolicy must have at least one requirement."
Is this a mistake in our component, or a general rule that any policy must have at least one Role or User?
If it is a general rule, it would be good if this could be validated/enforced on the editing page.

**Comment by joeaudette** [comment]
It is a general rule that an auth policy must have some requirement. But I think we could decide that we want to change a policy to not require any roles or claims so anonymous users are allowed. To make a policy like that requires adding a requirement function that always returns true. From a UI/UX perspective if I remove all requirements I would expect it to allow all users including anonymous users, I would not expect it to produce an error.

So we could enforce it in the UI to require at least one role or claim. But maybe a better option would be if it has no requirements then automatically add a function that returns true so it will allow access to all users and won't throw an error. We could augment that with a warning indicator in the UI that shows in bold that "This policy currently allows anonymous users, if that is not intended please add a requirement."

@CrispinF thoughts?

**Comment by CrispinF** [comment]
I admit was actually expecting the opposite: I assumed that when I removed all roles, and there were no users, that nobody would be able to do the thing. That's exactly what I wanted.
But I didn't think about this very deeply, and so don't have a problem to have it the other way around, _particular as there is the checkbox at the top for "Require Authenticated User"_ - it seems sensible that if that is blank and nothing else is specified, that means _anyone_ can do the thing.

But that would not have helped in my scenario... I'll explain a little more... the policy in question was showing lots of extra clutter in an administrative bit of UI. I didn't need any of that functionality in this particular project, so I just wanted it to disappear from me as Administrator role. That was the only role on the Policy, so I assumed removing it would have the effect.
So I'd have preferred it in this particular scenario if it defaulted to False. But this case was rather unusual, and overall the default to True is perhaps more intuitive, though it is more risky to default to "all" rather than "none".

**Comment by joeaudette** [comment]
I've implemented the automatic use of a requirement function that allows anonymous access and warnings on the edit page for policies that do allow anonymous access. New nugets published.

For your scenario a workaround is create a role for "Thing you don't care about - Managers" with no members and use that as the only allowed role.
