### ISSUE TITLE
Option to enforce only one active session per user

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#615]
A request/idea from a client. 
They know that users in a membership benefits system are sharing logins with friends so they don't have to pay.   We know we can help counter this by adding some more logging, but they would like to prevent it more proactively if possible.
So... possible implementation:
on each request (that is not a login action) we check whether the requesting ip matches the active (last recorded) i.p. for the current user (some extra storage required). If it does not, log the user out and treat the request as unauthenticated. 
When a user logs in, this always wins, and we record this i.p. as the active one.
So last login wins. If one user is working across several devices and locations this is all fine. If people are sharing a login between friends, it will be highly frustrating as they will be competing for a session.
Operating in this mode would obviously not be desirable on many sites, as it would sign users out even when they clicked Remember Me, if they use same login from different computers.
So it would be a site-wide configuration option to put it into this mode.
Thoughts?

**Comment by joeaudette** [comment]
This is very doable, estimate 1-2 hours to implement and test.

If we add a new field on siteuser for the loginipaddress and a new boolean field on sitesettings whether to enforce single session per user, the the [EnforceSiteRulesMiddleware](https://github.com/cloudscribe/cloudscribe/blob/master/src/cloudscribe.Core.Web/Middleware/EnforceSiteRulesMiddleware.cs) could be updated to sign the user out of the current authenticated request is from a different ip address.

**Comment by CrispinF** [comment]
@joeaudette OK I'll see if the client wants to proceed, and if so we'll sponsor this development.

**Comment by joeaudette** [comment]
Some additional thoughts on this. Phones and mobile devices can have their ip address change while in use so it would be possible for a user who is not sharing their login to be impacted negatively by our current plan. ie the user logs in, they drive somewhere and maybe end up with a different ip while roaming.

So an additional mitigation to avoid that negative impact would be to also add a LoginIpAddress claim to the user. This way we know if the claim matches the current last login ip in the db then even if the current ip is different we should not forcefully sign the user out. If another user logs in from a different ip address then the db ipaddress will change and would no longer match the claim.

So the logic would be any authenticated user whose ipaddress does not match the db ipaddress and whose LoginIpAddress claim does not match the db ipaddress will be forcefully signed out if the site setting indicates forcing a single user session.

**Comment by joeaudette** [comment]
yet another thought on this. Maybe ipaddress is not how we should tackle this because some scenarios will want to prevent also more than one web browser session by the same user. ie if a user logs in with Chrome they should not be able to have a simultaneous session in Edge or Firefox.

So maybe at login time we should store a random LoginGuid and also assign a LoginGuid claim, then the logic can be if the claim doesn't match the db then force sign out. Every time the user logs in the guid would be regenerated so the claim would not match and we would achieve the same result but even more strictly preventing multiple sessions by the same user even if the ipaddress is the same.

**Comment by CrispinF** [comment]
@joeaudette so the session would be truly linked to the browser in which the user logged in, yes?  Without causing disruption for mobile users. All sounds good, eg in preventing different people in one (say) family or company sharing an account.
It might be bothersome for testing in different browsers, but that would normally be done in an environment where this could be switched off.

**Comment by joeaudette** [comment]
This has been implemented and nugets published.
