### ISSUE TITLE
Bug: File Browser Issue Immediately uploading files without hitting the upload button

### ISSUE THREAD

**Issue by hsankala** [cloudscribe/cloudscribe#627]
Little buglet that needs a squashing!

I think the issue might have crept in when I updated nuget package cloudscribe.Core.Web to v3.1.80. When I brought it in it updated dependent nugets not sure which though.

Issue 
--------- 
1. Create vanilla website with CS project template 1.75, Update all CS nugets
2. Goto Admin -> File Manager
3. Create folder 'Test' and select
4. Goto 'Upload' tab and drag and drop some photos onto the page to upload
**Issue** The photos are immediately uploaded without the upload button being pressed the files names disappear in an instant

Here's my nuget list from CSProj should be the latest as of right now

   `<PackageReference Include="cloudscribe.Core.Web" Version="3.1.80" />
    <PackageReference Include="cloudscribe.Core.CompiledViews.Bootstrap4" Version="3.1.42" />
    <PackageReference Include="cloudscribe.Web.StaticFiles" Version="1.0.12" />
    <PackageReference Include="cloudscribe.Core.Storage.EFCore.MSSQL" Version="3.0.18" />
    <PackageReference Include="cloudscribe.Core.SimpleContent" Version="4.0.13" />
    <PackageReference Include="cloudscribe.SimpleContent.Web" Version="4.0.36" />
    <PackageReference Include="cloudscribe.Core.SimpleContent.CompiledViews.Bootstrap4" Version="4.0.11" />
    <PackageReference Include="cloudscribe.SimpleContent.CompiledViews.Bootstrap4" Version="4.0.27" />
    <PackageReference Include="cloudscribe.SimpleContent.MetaWeblog" Version="4.0.9" />
    <PackageReference Include="cloudscribe.SimpleContent.Syndication" Version="4.0.6" />
    <PackageReference Include="cloudscribe.SimpleContent.ContentTemplates.Bootstrap4" Version="1.0.18" />
    <PackageReference Include="cloudscribe.SimpleContent.Storage.EFCore.MSSQL" Version="4.0.12" />
    <PackageReference Include="cloudscribe.Logging.Web" Version="3.0.10" />
    <PackageReference Include="cloudscribe.Logging.EFCore.MSSQL" Version="3.0.9" />
    <PackageReference Include="cloudscribe.Web.Localization" Version="2.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.App" />`

**Comment by joeaudette** [comment]
No that is a new feature, see my latest comments in #622, files now auto upload upon selection.

**Comment by hsankala** [comment]
haha new feature! coolio

**Comment by joeaudette** [comment]
Actually I did just find a bug, after uploading the files it reloads the folder sub tree too fast. The problem with that is it sees the files before they have been resized and before the full sized ones are deleted. ie it shows the full size file names but then clicking them they are blank because by now they have.
I need to add a timeout before reloading the folder.

**Comment by joeaudette** [comment]
ok, just published updated nugets again. Added a 3 second wait after the upload requests finish before reloading the folder in the browse tab to allow the server time to finish processing the files.

Note also I added an extra checkbox for the upload tab in case you want to keep the originals when bulk uploading and resizing.
