### ISSUE TITLE
404 /cr/js/cloudscribe-logout-link.js

### ISSUE THREAD

**Issue by trendoid** [cloudscribe/cloudscribe#640]
I tried out the code using the CLI to build a site.  After logging in, I couldn't logout.  I clicked the link but nothing happened.  With all the different repos, I wasn't sure if this is a Template bug or a Core bug.

{"Id":"48996a04-5655-4faa-b3bb-49f78cc88c95","LogDateUtc":"2019-06-23T17:20:11.488871Z","IpAddress":"::1","Culture":"en-US","Url":"/oops/error/404","ShortUrl":"/oops/error/404","Thread":"","LogLevel":"Warning","Logger":"cloudscribe.Core.Web.Controllers.Mvc.OopsController","Message":"handled 404 for url: /cr/js/cloudscribe-logout-link.js GET from ipaddress ::1","StateJson":"[{\"Key\":\"{OriginalFormat}\",\"Value\":\"handled 404 for url: /cr/js/cloudscribe-logout-link.js GET from ipaddress ::1\"}]","EventId":0}

**Comment by joeaudette** [comment]
First thing to do after creating a project is update to all the latest cloudscribe nugets. That should solve it, if not let me know.

**Comment by joeaudette** [comment]
@trendoid did you update the nugets? Can I close this?
