### ISSUE TITLE
Dynamic Authorisation Policies - list view to give some clue as to whether/how each has been configured

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#642]
At present the list of policies gives no clue which ones have been configured. We see just the name and the Edit link.  It would great to see some indication of whether each has been modified. One method might be to show a count of roles associated with the policy, or whether a named user is assigned. The default is 1 role (Administrators) so any with 1 are likely unconfigured.
So each row might display:
MyPolicy   Roles: 2  (+ named user)
MyOtherPolicy   Roles: 4
MyThird Policy   Roles: 0 (+ named user)

but maybe with the data in tidier columns!  Another way might be date/time last mod, but I don't know if we have those in the table, and I think the above would be more useful.

PS is this logged in the right repo?

**Comment by joeaudette** [comment]
This has been implemented and new nugets published. 

Dynamic Auth is a product, not open source so it doesn't have a public repo. This repo is fine for issue tracking for now, eventually we will have forums on cloudscribe.com and that will be a better place to ask about add on product features.
