### ISSUE TITLE
What happen if there is not any layout in the project?!

### ISSUE THREAD

**Issue by mikeandersun** [cloudscribe/cloudscribe#662]
I rename `sharedTenes` and  delete `_Layout.cshtml` in `custom1` theme in `/sitefiles/s1/themes/custom1` but no any change effects in the UI!
Where is the default theme?!

**Comment by joeaudette** [comment]
A layout file local to the web app will always be used if it exists but if not, there is a layout file in the views nuget
https://github.com/cloudscribe/cloudscribe/blob/master/src/cloudscribe.Core.CompiledViews.Bootstrap4/Views/Shared/_Layout.cshtml
