### ISSUE TITLE
Allow adding a role to a user on the user management page

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#666]
Following on from #367 it would be really nice to be able to add a role to a user rather than having to go to the role management page.
Similar pattern (to adding a user to a role) would be good: click "Add" > modal list of roles each with "Add" button, and a Close button bottom right.  The number of roles should not be large, but the list needs to accommodate paging for when it is. I don't think it needs a search capability.

**Comment by JimKerslake** [comment]
This is tractable but is likely to open up a few anomalies and potential security issues that need to be considered.

The immediate one that I'm aware of (and will try to avert) is that only Admins can add other users to Admin role, although non-admins may potentially be granted privs to use the User Management UI.   That Admin role is 'special'.
That's just an illustrative one - there may well be others similar.

**Comment by JimKerslake** [comment]
cloudscribe.Core.CompiledViews.Bootstrap5  6.0.21
cloudscribe.Core.Storage.EFCore.Common  6.0.2
cloudscribe.Core.Storage.NoDb  6.0.2
cloudscribe.Core.Web 6.0.33
cloudscribe.Web.StaticFiles  6.0.9

**Comment by JimKerslake** [comment]
Needs a bit of a test - I struggled a little when there are sufficient roles to invoke the paging, making sure that selected 
 checkboxes on multiple pages can persist across further page-changing and get posted back OK.

**Comment by CrispinF** [comment]
All good and released.
