### ISSUE TITLE
Question: Steps to upgrade to 3.0

### ISSUE THREAD

**Issue by abomadi** [cloudscribe/cloudscribe#669]
Hello Joe,

Any steps / recommendations on how to upgrade to 3.0 ?

**Comment by CrispinF** [comment]
Hi @abomadi we're working on all the cloudscribe nugets for Core 3.0 and most are now published with changes to the major version number. You'll see these if you "Manage NuGet Packages" in your solution.

We’ve not yet had a chance to write up detailed instructions, but you could get things working by following the Microsoft documentation e.g. https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio 

You need the .NET Core 3.0 SDK installed from here https://dotnet.microsoft.com/download plus latest Visual Studio 2019, and the equivalent runtime on your server.

Hope this helps - let us know how it goes!

**Comment by abomadi** [comment]
It went good so far, however some bugs did show due to the sdk migration, 
api/rss api/sitemap have to be asynchronous also 2f authentication drop and error still investigating

**Comment by joeaudette** [comment]
@abomadi those issues should be fixed in the latest nugets.

**Comment by abomadi** [comment]
@joeaudette Thanks, all good so far, going to close this one
