### ISSUE TITLE
.NetFramework8 is needs to run cloudscribe?

### ISSUE THREAD

**Issue by mikeandersun** [cloudscribe/cloudscribe#675]
I reinstall windows 10 on my PC and install VS.NET 2019 community. 
This is the error when run the application.
I need to install .NetFramework 8 manually?
`Error	MSB3086	Task could not find "al.exe" using the SdkToolsPath "" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.2\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool exists in the correct processor specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed	cloudscribe.Web.StaticFiles	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	3639		
`

**Comment by joeaudette** [comment]
What application, the one in this repo?

Have you googled the error?

Seems like a tooling issue not a cloudscribe issue.

**Comment by mikeandersun** [comment]
> What application, the one in this repo?

YES

**Comment by mikeandersun** [comment]
I Install Windows 10 SDK. Then add `TargetFrameworkSDKToolsDirectory `  path variables in windows paths according [this](https://stackoverflow.com/questions/2986440/msbuild-on-ci-server-cant-find-al-exe) conversation on SO.

**Comment by CrispinF** [comment]
Great to hear that is solved @mikeandersun
