### ISSUE TITLE
User management Search should not be case-sensitive (affects PGSQL, NoDB)

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#679]
/useradmin page Search function with PGSQL database is case sensitive. So can fail to find an existing user if search for jimk@gmail.com instead of JimK@gmail.com.  But if you then proceed to try to create a user as jimk@gmail.com it will fail saying the email already exists.
This search should not be case-sensitive, and it is not case-sensitive when using SQL Server.
Noticing the search is also case sensitive using NoDB. Therefore possibly other storage options too.

**Comment by JimKerslake** [comment]
I think the same is true on MSSQL, for me running locally at least

**Comment by SimonAnnetts** [comment]
uploaded new packages:
cloudscribe.Core.Storage.EFCore.Common.4.0.3.nupkg
cloudscribe.Core.Storage.NoDb.4.0.1.nupkg

**Comment by CrispinF** [comment]
As discussed, I think we also need to bump the DB-specific packages e.g. cloudscribe.Core.Storage.EFCore.PostgreSql

**Comment by SimonAnnetts** [comment]
cloudscribe.Core.Storage.EFCore.MSSQL
cloudscribe.Core.Storage.EFCore.MySql
cloudscribe.Core.Storage.EFCore.pgsql
cloudscribe.Core.Storage.EFCore.PostgreSql
cloudscribe.Core.Storage.EFCore.SQLite
all bumped to 4.0.3

**Comment by CrispinF** [comment]
@SimonAnnetts this is failing with PGSQL:
07/05/2020 20:50:12 Error xx.xx.xx.xx Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware /librarylink/useradmin/search

An unhandled exception has occurred while executing the request. System.InvalidOperationException: The LINQ expression 'Where<SiteUser>( source: DbSet<SiteUser>, predicate: (s) => s.SiteId == (Unhandled parameter: __siteId_0) && False || s.Email.Contains( value: (Unhandled parameter: __searchInput_1), comparisonType: OrdinalIgnoreCase) || s.UserName.Contains( value: (Unhandled parameter: __searchInput_1), comparisonType: OrdinalIgnoreCase) || s.FirstName != null && s.FirstName.Contains( value: (Unhandled parameter: __searchInput_1), comparisonType: OrdinalIgnoreCase) || s.LastName != null && s.LastName.Contains( value: (Unhandled parameter: __searchInput_1), comparisonType: OrdinalIgnoreCase) || s.DisplayName.Contains( value: (Unhandled parameter: __searchInput_1), comparisonType: OrdinalIgnoreCase))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync().

**Comment by JimKerslake** [comment]
EF (for Postgresql only) can't parse the C# linq expressions back into suitable pgSQL, and these days EF Core 3 throws an exception when it can't do that.

**Comment by SimonAnnetts** [comment]
cloudscribe.Core.Storage.EFCore.MSSQL
cloudscribe.Core.Storage.EFCore.MySql
cloudscribe.Core.Storage.EFCore.pgsql
cloudscribe.Core.Storage.EFCore.PostgreSql
cloudscribe.Core.Storage.EFCore.SQLite
all bumped to 4.0.5
cloudscribe.Core.Storage.NoDb
bumped to 4.0.4

**Comment by CrispinF** [comment]
Tested OK against postgreSQL v11, and the searching is now case insensitive.
@SimonAnnetts are we OK to close this now or do we need more testing against other DB platforms?

**Comment by SimonAnnetts** [comment]
@CrispinF 
Tested against all DB providers except old-pgsql driver.
Postgresql
MySql
MSSQL
SQLite
NoDb
