### ISSUE TITLE
User Management Page - layout issue

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe#680]
Long user names and email addresses are causing the user management table to drop to the bottom of the screen, leaving lots of white space.

![image](https://user-images.githubusercontent.com/10956017/68754535-c9946880-05fe-11ea-9a9f-ddc1c306328a.png)

There is nothing in the markup that allows a developer to write css rules to address this behaviour, e.g. use word-break to force the columns concerned to wrap their content.

I suggest adding a css class to the table so that a developer can write css rules targeting it.

A better long term fix might be to look at rendering markup that flows better than a table.

**Comment by CrispinF** [comment]
We've seen this in a lot of sites, and it needs to be sorted out.

**Comment by SimonAnnetts** [comment]
I've added a class to the table and classes to the td columns so you should be able to style it the way you want. I've included some styling in the default theme scss in the sourceDev.WebApp project which fixes the problem you highlighted.

~~~
.usergrid-table {
    width: 100%;
}
.usergrid-column2 {
    word-break: break-word;
}
.usergrid-column4 {
    word-break: break-word;
}
.usergrid-column5 {
    word-break: break-word;
}
~~~

![image](https://user-images.githubusercontent.com/725219/79354531-6f445e80-7f34-11ea-8a0c-7ea531ed1c73.png)

You'll need cloudscribe.Core.CompiledViews.Bootstrap4.4.0.4 nuget for this.

**Comment by CrispinF** [comment]
Thanks @SimonAnnetts 
Tested ok - in that I can see all the new classes in a deployed site. 

I'm now wondering whether/how we should add the css fixes into the various default themes supplied by the VSIX template? Because this problem can affect every site. Thoughts?

**Comment by CrispinF** [comment]
@StewartBellamy could you also review please as you first raised this?

**Comment by StewartBellamy** [comment]
@SimonAnnetts @CrispinF  - We could add the css to cloudscribe.Web.Static files or (and I prefer this) use the BS4 text utility classes direct on the BS4 view. https://getbootstrap.com/docs/4.3/utilities/text/#word-break

**Comment by SimonAnnetts** [comment]
@StewartBellamy @CrispinF I guess the latter would be preferable as it would mean we would not need update and ship extra CSS in all the VSIX templates or add the CSS to Static files. We would loose the ability to choose which columns get the word-break css though, and would hard code the BS4 class 'text-break' into columns 2,4 and 5

**Comment by CrispinF** [comment]
@SimonAnnetts if you keep the new class on the table and each column, and use the BS4 classes on the columns most likely to break, then we have a better default plus ability to further customise in individual projects, and don't need to ship extra css.
