### ISSUE TITLE
Make a TagHelper for theme images

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#689]
Along same lines as the existing ones in https://github.com/cloudscribe/cloudscribe/tree/master/src/cloudscribe.Core.Web/TagHelpers we could have one for images, so that theme images can be in a subfolder of the theme wwwroot. Then we will be able to reference images in _Layout.cshtml eg like this:
`<img class="mr-3" style="height:100px;" src="~/img/logo.jpg" alt="my logo" cs-resolve-theme-resource="true" cs-shared-theme="true" cs-tenant="@Tenant" />`
This helps keep a theme self-contained and so easier to re-use.

**Comment by SimonAnnetts** [comment]
update package to cloudscribe.Core.Web.4.0.9

@CrispinF are you able to easily test this in an existing site?

**Comment by CrispinF** [comment]
Yes, can do, and will report back.

**Comment by CrispinF** [comment]
Works nicely in a shared theme.
We should update this documentation page https://www.cloudscribe.com/themes-and-web-design as it specifically says there is no taghelper for images.
@SimonAnnetts can you confirm it behaves exactly the same as for js/css now?

**Comment by SimonAnnetts** [comment]
@CrispinF the code was mostly copied from the ThemeTagScriptHelper and targets the src tag in exactly the same way.

**Comment by SimonAnnetts** [comment]
Documentation updated.
