### ISSUE TITLE
Improve the email notification when "Require confirmed email" is ticked

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#691]
A user has remarked that the email that is sent looks "badly spammy".
Example:
![image](https://user-images.githubusercontent.com/10574730/79054862-5f7cff80-7c40-11ea-855f-470dc3dffe8f.png)

There's a typo: "Or submit this codeon the website form."

And the code is so long that the email body is forced far wider than most users will be able to display, so the result looks terrible.

Need to review how this code is generated any whether it needs to be so long. 

Or simpler solution:  just drop this section from the email. What's wrong with just the link?

**Comment by SimonAnnetts** [comment]
Here's what I receive in my email client (Thunderbird) when sending from the cloudscribe/sourceDev.WebApp project:
![image](https://user-images.githubusercontent.com/725219/79233376-acd7b780-7e60-11ea-83bc-98c12642bc45.png)

**Comment by SimonAnnetts** [comment]
and here is it in Outlook:
![image](https://user-images.githubusercontent.com/725219/79235551-ac8ceb80-7e63-11ea-8509-df7b22ea95d5.png)

**Comment by SimonAnnetts** [comment]
When you use 'click here to view it in a web browser' the email looks like it does in thunderbird. So I suspect some bad HTML in the email somewhere. I will also look to fix the text.

**Comment by SimonAnnetts** [comment]
Ok, I find this difficult to believe, but Outlook cannot display a textarea in a HTML email !! ?? I sent an HTML test email from thunderbird containing just a line of text and a textarea with rows=5 and cols=55

Viewed in Thunderbird:
![image](https://user-images.githubusercontent.com/725219/79238721-a7ca3680-7e67-11ea-8e31-a6746446b27d.png)

Viewed in Outlook:

**Comment by SimonAnnetts** [comment]
Changing the textarea to a table cell with wrapping looks much better in Outlook:
![image](https://user-images.githubusercontent.com/725219/79242495-52445880-7e6c-11ea-8556-a39538d10abc.png)

**Comment by SimonAnnetts** [comment]
Bumped cloudscribe.Core.CompiledViews.Bootstrap nuget to 4.0.1

**Comment by CrispinF** [comment]
This is looking good - tested in a deployed site.
I'm going to raise another issue to tidy up the text you see after confirming:
![image](https://user-images.githubusercontent.com/10574730/79276760-7faaf980-7ea0-11ea-9a5a-c56e25e665f6.png)
