### ISSUE TITLE
Markdown editor: drag and drop image fails if the image doesn't require resizing

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#692]
If the dropped image is large enough to require resizing, this works. If not, the JSON response is missing the resizedUrl value. Here's a complete example response that works:

`[{"resizedUrl":"/media/images/fanart-ws.jpg","thumbUrl":"","originalUrl":"/media/images/fanart.jpg","name":"fanart.jpg","length":59605,"type":"image/jpeg","dataId":null,"errorMessage":null}]`

If resizedUrl property is empty, nothing is inserted into the editor.

**Comment by SimonAnnetts** [comment]
Bumped cloudscribe.Web.StaticFiles nuget to 3.0.1

**Comment by CrispinF** [comment]
Tested OK.
