### ISSUE TITLE
MySqlException when starting for first time

### ISSUE THREAD

**Issue by BertHG** [cloudscribe/cloudscribe#693]
I always get the following error when I try to start the web application for the first time. The database is succesfully created.

`MySqlException: Unknown column 'c.CookiePolicySummary' in 'field list'
MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask<ArraySegment<byte>> task) in ServerSession.cs, line 775
MySqlException: Unknown column 'c.CookiePolicySummary' in 'field list'
MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in MySqlDataReader.cs, line 116`

**Comment by CrispinF** [comment]
@BertHG are you using the Visual Studio template?
Could you try again and this time go to Manage Nuget Packages > Updates and select all cloudscribe updates. 
Then try to start the web application, and let us know if you still see errors.
thanks!

**Comment by BertHG** [comment]
I made the project with the Visual Studio extension. I did all the updates. Only the Newsoft JSON couldn’t update because it wasn’t compatible with the ASP.NET Core version

**Comment by CrispinF** [comment]
OK we'll need to test this - could be a bug.
NB to get the Newtonsoft update, change this line in csproj
<TargetFramework>netcoreapp3.0</TargetFramework>
to this
<TargetFramework>netcoreapp3.1</TargetFramework>
then try the update again.
But I don't think that will fix the MySQL issue.
Maybe in the meantime you can make some progress with one of the other storage options... SQLite, NoDb, MSSQL, PGSQL...?

**Comment by BertHG** [comment]
I just changed the TargetFramework and updated the Newtonsoft package. Everything is updated at the moment but the error stays there. I can't really choose another storage option because I'd like to integrate an existing project with CloudScribe to use the user management and multi-tenant structure.

**Comment by SimonAnnetts** [comment]
@BertHG I have tried to re-create this error you are seeing, but it all works for me. I am using a different environment however - but here is the process I followed:

Here's my environment:
OS - Linux
Editor - vscode
MySQL version 5.7.29
.Net Core SDK - 3.1.201

I pre-created a database called 'cloudscribe' in MySQL with encoding utf8mb4_general_ci and granted all permissions to it to a user called 'cloudscribe'.

I have the cloudscribe project template installed 
~~~
dotnet new -i "cloudscribe.templates::*"
~~~
so created a new cloudscribe project:
~~~
mkdir cloudscribe
cd cloudscribe
dotnet new cloudscribe -D mysql -S a -M None -Ke 5000 -H 5001
~~~
Restore packages:
~~~
dotnet restore
npm install
~~~
Fix the binary node_modules for Linux (not needed if you're on Windows):
~~~
rm -Rf node_modules/node-sass
npm install node-sass
~~~
Build the Site CSS:
~~~
gulp buildCustom1ThemeCss
~~~
Edit appsettings.Development.json and set the connection string:
~~~
  "ConnectionStrings": {
    "EntityFrameworkConnection": "Server=localhost;Database=cloudscribe;Uid=cloudscribe;Pwd=SETYOURPASSWORDHERE;Charset=utf8;"
  },
~~~
And lastly
~~~
dotnet run
~~~
I get no errors on startup and the database is filled with tables.

I checked and the table cs_Site contains a column CookiePolicySummary.

Can you provide a summary of the steps you took, and the versions of things? 
If possible could you list the last record you have in your __EFMigrationsHistory table?

**Comment by BertHG** [comment]
My environment:
Windows 10
Visual Studio Community 2019
Project created with CloudScribe extension
External database server '10.1.44-MariaDB-0ubuntu0.18.04.1'

Tables are created in the database but cs_Site is empty

All I did was: created project with the extension, changed the line in appsettings, update all nuget packages and run with IIS Server Express.

Last record in __EFMigrationsHistory: `'20170915201520_changes20170915', '3.0.0'`

**Comment by SimonAnnetts** [comment]
ah, looks the migrations did not complete.
Did you start with an empty database (i.e. no tables) or did you try updating an older installation?
Do you have a cs_UserToken table in your DB?

**Comment by BertHG** [comment]
I did start with a new empty database. 
These are the tables I have in the database:
`'__EFMigrationsHistory'
'cs_GeoCountry'
'cs_GeoZone'
'cs_Role'
'cs_Site'
'cs_SiteHost'
'cs_SystemLog'
'cs_User'
'cs_UserClaim'
'cs_UserLocation'
'cs_UserLogin'
'cs_UserRole'
`

**Comment by SimonAnnetts** [comment]
I'm not sure that MariaDB 10.1 is fully supported by Cloudscribe. You need MariaDB 10.3 or 10.4.
Cloudscribe uses this package:
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

You could see why the next migration failed. It should have done this:

~~~
      CREATE TABLE `cs_UserToken` (
          `UserId` char(36) NOT NULL,
          `SiteId` char(36) NOT NULL,
          `LoginProvider` varchar(128) NOT NULL,
          `Name` varchar(450) NOT NULL,
          `Value` longtext NULL,
          CONSTRAINT `PK_cs_UserToken` PRIMARY KEY (`UserId`, `SiteId`, `LoginProvider`, `Name`)
      );
     CREATE INDEX `IX_cs_UserToken_SiteId` ON `cs_UserToken` (`SiteId`);
     CREATE INDEX `IX_cs_UserToken_UserId` ON `cs_UserToken` (`UserId`);
~~~

**Comment by BertHG** [comment]
Strange. I'm using this version with another ASP.NET database and in that project I also use Pomelo.EntityFrameworkCore.MySql. I'll need to try it with another version of MariaDB in the future and will let you know if that solves the problem. At this moment I can't test it because I'll need to set up another instance

**Comment by SimonAnnetts** [comment]
Ok thanks. It may also be that Cloudscribe needs to upgrade to a newer Pomelo.EntityFrameworkCore.MySql package. Currently it's using 3.0.0, but I see there is a 3.0.1 for EF 3.0.x

**Comment by SimonAnnetts** [comment]
Are you able to run that SQL I posted above on your 10.1 instance? It might give a clue as to why the migration is failing...

**Comment by joeaudette** [comment]
Have you tried starting again with an empty db now that all the nuget packages are updated? If you initially ran it without getting the latest nugets it could be a problem created by an old nuget package.

**Comment by BertHG** [comment]
Yes I tried that. I ran the SQL from Simon and now I get the following error:
`Error Code: 1071. Specified key was too long; max key length is 767 bytes	0.042 sec`

**Comment by joeaudette** [comment]
That must be a difference between mariadb and mysql, I guess it doesn't like the combined length of the multi-column primary key.

**Comment by BertHG** [comment]
Okay thanks for the information. Than I'll need to migrate to MySQL if I want to use CloudScribe.

**Comment by CrispinF** [comment]
There's some possibly relevant suggestions here https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes
e.g. SET @@global.innodb_large_prefix = 1; 
to raise the threshold. I don't know if this applies in MariaDB though, or whether it has any downsides.

**Comment by SimonAnnetts** [comment]
This key length was increased to 3072 bytes in MariaDb 10.2
The length of the primary key in that table is (36+36+18+450 ) *4 = 2160 assuming utf8mb4_general_ci encoding (4 byte UTF8)

**Comment by BertHG** [comment]
I just upgraded to 10.2 and it works! Thank you guys!

**Comment by CrispinF** [comment]
@BertHG great news.  However, we're not aware of any rigorous testing/use of cloudscribe + MariaDB, so please keep an eye for other issues and let us know! Closing this issue assuming you're happy.
