### ISSUE TITLE
In a FolderName multi-tenant site with UseRelatedSitesMode registration fails in tenant

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#705]
With these settings:
```
    "MultiTenantOptions": {
    "Mode": "FolderName",
    "UseRelatedSitesMode": "true",
```
and with "Require approval before login"=1 in both sites, registration in the master/parent site works fine, but registration in the child site fails to create a new user.  It appears to work, to the user, and email notifications are sent, but the account is not created. Nothing appears in the system log.
This has been observed in cloudscribe.Core.Web 3.1.100 and cloudscribe.Core.Web 4.0.6.

_Interim recommendation: switch off "Allow registration" in the child site(s) and instead direct new users to register in the master site._

**Comment by joeaudette** [comment]
using related sites mode requires populating the RelatedSiteId

**Comment by CrispinF** [comment]
@joeaudette yes, that's populated in the sites I'm testing in.

**Comment by CrispinF** [comment]
Extra info: if "Require approval before login"=0 in the tenant site, then registration in the tenant initially appears to succeed. The user sees "Hello xxx" and seems to be logged in, but then gets signed out again on next click. The new user notification email is sent, but no account created (and nothing in System Log).

**Comment by joeaudette** [comment]
Most likely the site rules middleware is involved. If producing the issue in a dev environment I would set breakpoint there.

**Comment by CrispinF** [comment]
Note that creation of the user also fails when done by a site administrator in the tenant (with nothing in the system log).
Also that this bug already existed in .NET Core 2.* (I've just tested in an old multi-tenant site).

**Comment by JimKerslake** [comment]
The user was actually created fine in the database.  
However its Site Id was set to the Guid of the tenant site.
Meanwhile the data access code that renders the available users out onto the UI is set to query only for users from the RelatedSiteId, when running in related sites mode  
(so any users created from the tenant site would seem to vanish from the UI).

Decided that new users created in related sites mode should always acquire the site Id of the RelatedSiteId (most probably the main parent site), even if they are created from the tenant site.

Pushing cloudscribe.Core.Identity to v.4.0.1
cloudscribe.Core.Web to v.4.0.8
(Wants a thorough test)

**Comment by CrispinF** [comment]
Testing this in a multi-tenant site in related sites mode. 
Registration in the main site and the child site both now work fine, resulting in the same outcome. 
NB registration in each tenant does still obey its own config settings (requiring approval, require validated email, email notification), which can be useful, but can also get confusing!
