### ISSUE TITLE
Remove redundant AddEntityFramework* calls

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe#714]
Warning in the log:

`'AddEntityFramework*' was called on the service provider, but 'UseInternalServiceProvider' wasn't called in the DbContext options configuration. Remove the 'AddEntityFramework*' call as in most cases it's not needed and might cause conflicts with other products and services registered in the same service provider.`

See this github issue: https://github.com/dotnet/EntityFramework.Docs/issues/1371

`Don't call AddEntityFrameworkNpgsql or AddEntityFrameworkSqlServer anywhere. These aren't methods that applications should call under normal conditions.`

**Comment by StewartBellamy** [comment]
The exisiting code AddEntityFramework* should be replaced in line with this example.

Current code:
```
            services.AddEntityFrameworkSqlServer()
                .AddDbContext<CoreDbContext>(options =>
                    options.UseSqlServer(connectionString,
                        sqlServerOptionsAction: sqlOptions =>
```

Updated code:
            services.AddDbContext<CoreDbContext>((options) =>
                    options.UseSqlServer(connectionString,
                        sqlServerOptionsAction: sqlOptions =>

**Comment by StewartBellamy** [comment]
See also: https://github.com/dotnet/efcore/issues/12905

**Comment by SimonAnnetts** [comment]
@StewartBellamy 
Warning introduced in
https://github.com/dotnet/efcore/issues/19053
so only a problem if using Microsoft.EntityFrameworkCore 3.1.1 or above.
I think CS packages are currently using 3.0.0

**Comment by StewartBellamy** [comment]
@JimKerslake  - CS is now at 3.1, do we know if this is resolved?

**Comment by JimKerslake** [comment]
I remembered that one @StewartBellamy  - you complained about it one time previously, a few weeks ago :)

So during the recent CS upgrade I certainly removed those deprecated calls wherever I came across them.

(Whether I got rid of them all, everywhere... I could not swear to that... they were present in every CS project in which there were DB migrations.)

**Comment by JimKerslake** [comment]
(Outside of cloudscribe)...  
@StewartBellamy  I just noticed that our esdm PP search predictor (which uses migrations) still has the deprecated call in it - so there is potential for the warnings to come in from PP stack as well as CS - and at least one lurking case of it still to clobber there.
