### ISSUE TITLE
New Tenant Login doesn't work due to incorrect tenant ID

### ISSUE THREAD

**Issue by shubhamranjan** [cloudscribe/cloudscribe#725]
Hi,

I had setup a project using cloudscribe latest template and created another tenant. Whenever I try to login to that tenant, I get Invalid login attempt.

Steps to reproduce:

1. Create new project using visual studio template with PGSQL as backend, disable simple content and use hostname as tenant resolver.
2. Run Postgres and project. Create new tenant and user for that tenant.
3. Create host mapping for the new site as `site2.example.com`
4. Change launch settings to bind to any host instead of localhost.
`https://0.0.0.0:44320;http://0.0.0.0:14647`
5. Create a host entry on your machine for `site2.example.com` to point to `127.0.0.1`
6. Open a new tab / incognito tab and try to login. It fails.

I tried to debug by pulling the source code and found out that at `FindByEmailAsync` method of `cloudscribe\src\cloudscribe.Core.Identity\UserStore.cs`, an incorrect tenant ID is being picked up. The tenant ID was of site 1 (default site) instead of site 2 which results in login failure.

I am trying to go through the source code and trying to understand how the whole thing works and maybe would be able to find a root cause soon. 

Please do let me know if I am doing anything wrong above.

**Comment by joeaudette** [comment]
Did you update appsetting to make it use host name based multi-tenancy? The default is FolderName

    "MultiTenantOptions": {
    "Mode": "HostName",
    "UseRelatedSitesMode": "false",
    "RelatedSiteId": "",
    "RelatedSiteAliasId": ""
      }

**Comment by joeaudette** [comment]
https://www.cloudscribe.com/multi-tenant-support

**Comment by shubhamranjan** [comment]
> Did you update appsetting to make it use host name based multi-tenancy? The default is FolderName
> 
> ```
> "MultiTenantOptions": {
> "Mode": "HostName",
> "UseRelatedSitesMode": "false",
> "RelatedSiteId": "",
> "RelatedSiteAliasId": ""
>   }
> ```

Yeah I double checked this. I can confirm that this behavior is fine as the `site2.example.com` shows the correct Site Title in header.

**Comment by joeaudette** [comment]
If you can debug it then set breakpoints in [CachingSiteContextResolver](https://github.com/cloudscribe/cloudscribe/blob/master/src/cloudscribe.Core.Web/Components/CachingSiteContextResolver.cs) and in [SiteContextResolver](https://github.com/cloudscribe/cloudscribe/blob/master/src/cloudscribe.Core.Web/Components/SiteContextResolver.cs) to see what is happening when it tries to resolve the site from the host name

**Comment by shubhamranjan** [comment]
> If you can debug it then set breakpoints in [CachingSiteContextResolver](https://github.com/cloudscribe/cloudscribe/blob/master/src/cloudscribe.Core.Web/Components/CachingSiteContextResolver.cs) and in [SiteContextResolver](https://github.com/cloudscribe/cloudscribe/blob/master/src/cloudscribe.Core.Web/Components/SiteContextResolver.cs) to see what is happening when it tries to resolve the site from the host name

Thanks. This helped me figure out the issue.

So my site was mapped to `site2.example.com` and I was accessing site via `site2.example.com:44320`. While fetching the host details from the database, the port segment is also being passed (which is correct logically but no on usually does anything other than port 80).  

However, in `_Layout.cshtml`, this  line `var Tenant = await siteResolver.ResolveSite(Context.Request.Host.Host, Context.Request.Path);` is present which only provides the host except the port which leads to a key of  `site2.example.com`  be populated as well. 

So when I looked up the cache I had a correct value of `site2.example.com` and an incorrect value of `site2.example.com:44320` (because of port not being present in mapping).

You may want to check on the value that is being passed from the `_Layout`. It depends whether you want to give the feasibility of hosting on multiple ports or not.


Thanks for pointing me in the right direction. 

Also one more thing completely unrelated to this thread, are you willing to accept PR(s) related to 3.1 upgrade of the whole stack. Didn't give one right away as wasn't sure about your plans for the upgrade.

**Comment by joeaudette** [comment]
If you think changes are needed for 3.1 then start a new thread and explain what changes you think are needed and why. 

Unless there are breaking changes in our dependencies that we must handle then we are better off continuing to depend on lower versions so we have more compatibility. Users are free to update their apps to use 3.1 or newer and that determines which version is actually used. The versions we declare as dependencies are just the minimum version, unless there are breaking changes our libs are still compatible with newer versions of the framework.

**Comment by shubhamranjan** [comment]
Yeah users can however upgrade their app. Suggest the same as 3.0 is EOL and thats what the template generates and some of the libraries target netstandard 2.1 which itself removes version support for version lower than 3.0.  Breaking changes can be referred from here though: https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.0-3.1

**Comment by joeaudette** [comment]
I agree it would be a good idea for us to update our template to create new projects with 3.1 since 3.0 is EOL.

But it is fine for our libraries to target netstandard2.1 if they don't need anything that requires netcoreapp. It is also fine for our libraries to depend on 3.0 versions and we don't need to change them except in places where there are breaking changes that require changes in our code.
