### ISSUE TITLE
Identity Server latest version - breaking changes -> absolutely not working.

### ISSUE THREAD

**Issue by inpicksys** [cloudscribe/cloudscribe#728]

**Comment by CrispinF** [comment]
@inpicksys could you provide some more information on what you have tried that isn't working please?

**Comment by inpicksys** [comment]
Is project alive? e.g. IS4 changes their API, do you plan update it latest version of IS4?

**Comment by CrispinF** [comment]
@inpicksys could you provide some more information on what you have tried that isn't working please?
We are aware of one issue #712 and will be working on that soon, but it is easily worked around.
