### ISSUE TITLE
Identity server 4 with multi tenant support

### ISSUE THREAD

**Issue by abodehq** [cloudscribe/cloudscribe#731]
Dears great work,

My question is that i already  build an admin web app using .netcore 3.1 and i want to allow multitenant with identity server 4 which u already implement in your solution .

is there any guide on how i can implement only the multitenant project with identity server 4 without using the whole solution projects.

please i really appreciate your help.
thanks

**Comment by CrispinF** [comment]
Hi @abodehq please see https://www.cloudscribe.com/identityserver-integration
