### ISSUE TITLE
Upgrade automapper dependency

### ISSUE THREAD

**Issue by JimKerslake** [cloudscribe/cloudscribe#735]
to latest v10.1.1

This requires generating 6 new nugets
cloudscribe.Core.IdentityServer.EFCore.Common
plus the 5 database-specific ones that consume it.

**Comment by CrispinF** [comment]
This has been published and tested. @JimKerslake anything still to do or can we close?

**Comment by JimKerslake** [comment]
@CrispinF closing :)
