### ISSUE TITLE
Allow user to change their email address

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#738]
At present an administrator can change a user's email but they cannot change their own. This has been requested for a client project, and seems reasonable.
Things to consider:
- This should be optional, enabled with a site setting under /siteadmin/securitysettings checkbox for "Allow user to change email address".
- Where the site has "Require confirmed email" switched on, changing email should also require confirmation of the new email before the user can log in with the new one.
- Changing email should involve the same checks on uniqueness as registration (with due consideration of multi-tenant options).
- Whether any other information could hang off the email address (e.g. in membership module?).

**Comment by StewartBellamy** [comment]
I implemented this on a client project recently and emails went out to both addresses and the actual email address wasn't changed until the link in the confirmation email was clicked, which also contained single use time limited token.  I used an activations table to manage this and other 'activations'.  This might add more complexity but it does open it up for re-use and it means you don't have to store this info in the user table, just something to think about.

![image](https://user-images.githubusercontent.com/10956017/100070751-322d3c80-2e32-11eb-9c6f-6e5fc64a91a3.png)

So, in this scenario the activation type would be 'email change' and the 'data' would contain the new email address.

**Comment by joeaudette** [comment]
There are some existing fields in user table that could be used as well.

**Comment by CrispinF** [comment]
We have an offer of 50% sponsorship towards this issue, thanks to the Green Lane Association

**Comment by JimKerslake** [comment]
1 - Adding new setting to ISiteSettings (and migrations) 
but need to be mindful of the complication of Related Sites Mode:  since the user is then effectively shared across multiple sites, is it sane that one site would allow them to change email whilst another one won't.

**Comment by JimKerslake** [comment]
Functional issue:

Where the site has "Require confirmed email" switched OFF, then I think we should still send a notification email to old and new addresses, not just mutely implement the change  (although the change would be made in the Db without the additional confirmation email step).

Which means that we should not enable any of this UI email changing stuff unless 'EmailConfigured' is true (ie we have some SMTP settings or the equivalent configured). 

Changing a user's email in a system that has no email server settings configured would be pretty pointless - only of use for when people use email as a surrogate login user-id.

**Comment by CrispinF** [comment]
@JimKerslake can we discuss the above points please - there's a few more things to consider.

**Comment by CrispinF** [comment]
All looking good so closing this.
