### ISSUE TITLE
Parent property is empty

### ISSUE THREAD

**Issue by Netclick19** [cloudscribe/cloudscribe#745]
Hi,

is it possible that the Parent properties is empty for Model.CurrentNode?
The ParentChains values are present, but the Parent value not. 
My code worked well until 4.1.0 version.

Thank you for your support.

Kind regards.

**Comment by CrispinF** [comment]
@Netclick19 are you talking about https://github.com/cloudscribe/cloudscribe.Web.Navigation ?

**Comment by Netclick19** [comment]
Yes, sorry. 
I wrote in the wrong project!
