### ISSUE TITLE
Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer /api/sitemap Error in log

### ISSUE THREAD

**Issue by mfoitzik** [cloudscribe/cloudscribe#749]
I am getting the error below in my logs, however the sitemap api seems to be working fine ([https://www.simplicityblocks.com/api/sitemap](https://www.simplicityblocks.com/api/sitemap))

The error details seem to tell me what to do, but I am at a loss as to where (or if) I should be changing this. This is a fairly new project started early - mid last year so it started as an ASP.NET Core 3.1 version. Any help or pointers to the right direction would be appreciated.

ERROR IN LOG:

1/27/2021 9:22:02 AM Error 77.88.5.131 Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer /api/sitemap

Connection ID "14699749185347915162", Request ID "80000d9c-0000-cc00-b63f-84710c7967bb": An unhandled exception was thrown by the application. System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead. at Microsoft.AspNetCore.Server.IIS.Core.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count) at Microsoft.AspNetCore.Server.IIS.Core.WrappingStream.Write(Byte[] buffer, Int32 offset, Int32 count) at System.Xml.XmlUtf8RawTextWriter.FlushBuffer() at System.Xml.XmlUtf8RawTextWriter.Flush() at System.Xml.XmlWellFormedWriter.Close() at System.Xml.XmlWriter.Dispose(Boolean disposing) at System.Xml.XmlAsyncCheckWriter.Dispose(Boolean disposing) at System.Xml.XmlWriter.Dispose() at System.Xml.Linq.XDocument.SaveAsync(Stream stream, SaveOptions options, CancellationToken cancellationToken) at cloudscribe.Web.SiteMap.XmlResult.ExecuteResultAsync(ActionContext context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters() --- End of stack trace from previous location where exception was thrown --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker) at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext) at cloudscribe.Core.Web.Middleware.EnforceSiteRulesMiddleware.Invoke(HttpContext context, SiteContext currentSite, IOptions`1 multiTenantOptionsAccessor, IUserContextResolver userResolver, IAccountService accountService) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context) at cloudscribe.Multitenancy.Internal.TenantPipelineMiddleware`1.Invoke(HttpContext context) at cloudscribe.Multitenancy.Internal.TenantResolutionMiddleware`1.Invoke(HttpContext context, ITenantResolver`1 tenantResolver) at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task) at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

**Comment by JimKerslake** [comment]
Hi Mike

This looks like an issue that crept in with the Core 3.0 upgrade.
Another case of Microsoft "saving us from ourselves" by disabling synchronous actions like writing directly to the body of an HttpResponse (which the sitemap tries to do)... 
https://khalidabuhakmeh.com/dotnet-core-3-dot-0-allowsynchronousio-workaround

Even though that code chain is scrupulously asynchronous all the way, nonetheless it looks like we're not allowed to do things that way in Core 3.x.  There is a 'workaround' solution, but I'd prefer to see if I can change the code to avoid the issue properly rather than plugging in a workaround.   I'll post back here again shortly.

**Comment by JimKerslake** [comment]
@mfoitzik 

If you would like to try manually adding a reference to my new version of this package:
`    <PackageReference Include="cloudscribe.Web.SiteMap" Version="4.1.1" />`
then that seems to solve it for me.

If that's OK then I'll need to increment new versions of a couple more upstream cs NuGets that reference the SIteMap package, so that future template sites get it automatically.

I would not be surprised to see the same exception generated elsewhere in cloudscribe - I think there may be multiple uses of the technique that was being adopted here.

**Comment by mfoitzik** [comment]
@JimKerslake Hi Jim. I did the update this morning as you suggested and it took care of the problem. Thank you!

**Comment by JimKerslake** [comment]
You're welcome Mike, glad that it did the trick.
Thanks again for being our tester :)
All the best, Jim

**Comment by CrispinF** [comment]
@JimKerslake are we ready to close this or do you think another test needed? And is the version incrementing done?

**Comment by JimKerslake** [comment]
@CrispinF   I'll increment those extra few Nugets up the dependency tree tomorrow, then close.
