### ISSUE TITLE
Office365 SMTP fails (also any other relay over port 587)

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#755]
Using Office365 with setting like this:
```json
"SmtpOptions": {
    "Server": "smtp.office365.com",
    "Port": "587",
    "User": "crispin.flower@xxx",
	"Password": "xxx",
    "UseSsl": "true",
    "RequiresAuthentication": "true",
    "DefaultEmailFromAddress": "crispin.flower@xxx",
    "DefaultEmailFromAlias": ""
  },
```
fails to send with: 
An error occurred while attempting to establish an SSL or TLS connection.&#xD;&#xA;&#xD;&#xA;One possibility is that you are trying to connect to a port which does not support SSL/TLS.&#xD;&#xA;&#xD;&#xA;The other possibility is that the SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:&#xD;&#xA;1. The server is using a self-signed certificate which cannot be verified.&#xD;&#xA;2. The local system is missing a Root or Intermediate certificate needed to verify the server&#x27;s certificate.&#xD;&#xA;3. The certificate presented by the server is expired or invalid.&#xD;&#xA;&#xD;&#xA;See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions. stacktrace: at MailKit.Net.Smtp.SmtpClient.ConnectAsync

A mojoPortal site on the same server sends mail fine with the exact same settings.

**Comment by CrispinF** [comment]
NB this is from a site using a fairly old cloudscribe  
cloudscribe.Core.Web | 3.1.100

**Comment by CrispinF** [comment]
See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate
Possibly we need to set SecureSocketOptions.SslOnConnect in this line
https://github.com/cloudscribe/cloudscribe/blob/67366ba5a8066b5da76fa60c18f0a8dadc6dc669/src/cloudscribe.Email.Senders/Smtp/SmtpEmailSender.cs#L297
(unless that is anyway the default value?)

**Comment by CrispinF** [comment]
After some reading around and testing, we need to use SecureSocketOptions.StartTls when sending via Office365 SMPT over port 587. Because this is a special case, I'm adding a specific test for this scenario, leaving things unchanged otherwise.

It's worth noting that SMTP AUTH seems to be disabled by default these days in Microsoft365 (under "security defaults"), but it can be enabled for an organisation and a specific email account.

**Comment by CrispinF** [comment]
Subsequent testing of other services such as Mailgun showed that they also couldn't use their preferred port 587, but I found this started working with the above fix SecureSocketOptions.StartTls
So I've altered the code change to use this whenever the port is 587, and removed any mention of office365.

**Comment by JimKerslake** [comment]
@CrispinF 
Pushing a new version of cloudscribe.Email.Senders at 2.0.4

There's quite a widely scattered set of cs components that reference this at its earlier version - 
in theory I'd increment all of these.

However for the moment I would expect that a manual upgrade of just that one library from within a VS template solution should remedy the issue without conflicts.  Might be worth waiting to see if any user feedback requires another code revision before proceeding to pull all of these up too - else will end up doing it twice.

cloudscribe.SimpleContent.Web
cloudscribe.TalkAbout.Forum.Web
cloudscribe.TalkAbout.Web
cloudscribe.Cart.Web
cloudscribe.Forms.Web
cloudscribe.Temporal.Web
cloudscribe.EmailList.Web.Mvc
cloudscribe.EmailQueue.Services
cloudscribe.SimpleContactForm
