### ISSUE TITLE
Allow root site users to sign in to tenants (as a configured option)

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#760]
A request from a developer using cloudscribe.

The scenario is a multi-tenant site where customer users must have access only to their own tenant site, but employees of the service provider need to sign in on any tenant. At present, this requires creating an account in each tenant.
Initial thinking is we'd want a new global setting, applying to all tenants, like “RootUserCanSignInToTenants: true/false” (default false to preserve existing  behaviour). This setting would be only relevant with "UseRelatedSitesMode": "false". When in this mode, users are looked up in the tenant plus the site that has IsServerAdminSite set to true (typically the first site). Then company employees register in the root site, and they would be able to sign in to all tenants. And if these are folder-based tenants, their authentication would be remembered across all tenants.
 
I suspect there will be some complexities, around the various configurations and scenarios that are possible in cloudscribe, such as what roles the user gets in the tenant. Roles are not shared between sites when with "UseRelatedSitesMode": "false". Perhaps any users authenticated in this manner would be automatically assumed to be Administrators? Or perhaps there could be another config setting like “RolesForTenantSignInFromAdminSite”: “Content Administrators”. Or perhaps it could be looked up by matching role names between the root site and the tenant?

There may also be complexities around ownership and authorization in things like forums, Simple Content blog and pages.

**Comment by JimKerslake** [comment]
> we'd want a new global setting, applying to all tenants, like “RootUserCanSignInToTenants: true/false” (default false to preserve existing behaviour). This setting would be only relevant with "UseRelatedSitesMode": "false". 

Yes it feels a bit messy to have two config settings in conflict with one another - such that when the latter is true then the former must always be ignored.  (Because you could equally well specify that when the former is true then the latter must always be ignored... which is logically different.)

Will keep this very firmly on a dev branch and see how things pan out... will require a very thorough testing strategy.

**Comment by JimKerslake** [comment]
...in fact with RelatedSitesMode you are required to specify the RelatedSiteId as a guid, so that might not be the 'root' 'master' site.

@CrispinF  do you know what happens if you have UseRelatedSitesMode = true but leave that RelatedSiteId as zero guid?

(Wondering if this new thing is going to need a guid too, to specify which site we mean by root...)

**Comment by CrispinF** [comment]
@JimKerslake "the site that has IsServerAdminSite set to true"

**Comment by CrispinF** [comment]
After some initial investigations, we're starting some exploratory development to assess feasibility, working with a sponsor.

**Comment by CrispinF** [comment]
Early investigations are looking positive, but many questions and challenges remain. 
We're thinking a second appsetting should specify the guid of the site to consider the root/admin site.

@JimKerslake tests should cover (draft list):

1. When configured for this mode, can a user from the root site authenticate in the tenant?
2. What roles does the user acquire? (These should be the roles in the tenant site that match the user's roles in the root site by name).
3. With the user being in the Administrators role, can the user access Admin menu and Site Settings, all being for the tenant site?
4. Can the user access, create and configure users, roles, auth policies, in the tenant?
5. Can the user access protected SimpleContent pages in the tenant?
6. Can the user create and configure SimpleContent pages in the tenant?
7. Can the user access (and upload to) the files of the tenant using File Manager?
8. Can the user log out of the tenant?
9. In folder-based tenants, does all of the above apply when the user has authenticated in the root site and then visits the tenant? (Do they need to sign in again?).

Conversely:
1. When in related sites mode, has the introduction of this new mode changed anything? (this may not need empirical testing, just code review).

**Comment by JimKerslake** [comment]
I also don't know whether this configuration would work when used in combination with LDAP authentication or external OAuth.

**Comment by JimKerslake** [comment]
Reminder to self:
Consider requirement to supply new json config settings (new template required?), 
and test behaviour if they are absent.

**Comment by CrispinF** [comment]
@JimKerslake I don't think we need to make this available via template - documentation is sufficient. But yes, everything needs to work if settings absent, i.e. default to original behaviours.

**Comment by CrispinF** [comment]
This is currently in testing. Thanks to https://truedigitalsecurity.com/ for sponsorship. Packages and documentation are in prep.

**Comment by CrispinF** [comment]
@JimKerslake  With a NoDb hostname multi-tenant site, logging in to the tenant with a root site administrative account leads to this error:
10/09/2021 04:26:43 Error 31.125.19.169 Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer /

> Connection ID "16140901070401438250", Request ID "8000022b-0001-e000-b63f-84710c7967bb": An unhandled exception was thrown by the application. System.NullReferenceException: Object reference not set to an instance of an object. at cloudscribe.Core.Storage.NoDb.UserQueries.Fetch(Guid siteId, Guid userId, CancellationToken cancellationToken) at cloudscribe.Core.Identity.UserStore`1.FindByIdAsync(String userId, CancellationToken cancellationToken) at cloudscribe.Core.Web.Components.UserContextResolver.GetCurrentUser(CancellationToken cancellationToken) at cloudscribe.Core.Web.Middleware.EnforceSiteRulesMiddleware.Invoke(HttpContext context, SiteContext currentSite, IOptions`1 multiTenantOptionsAccessor, IUserContextResolver userResolver, IAccountService accountService) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context) at cloudscribe.Multitenancy.Internal.TenantPipelineMiddleware`1.Invoke(HttpContext context) at cloudscribe.Multitenancy.Internal.TenantResolutionMiddleware`1.Invoke(HttpContext context, ITenantResolver`1 tenantResolver) at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task) at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

We need to test to see whether this is a NoDb problem or a more general problem with the new mode with hostname multi-tenancy.

**Comment by CrispinF** [comment]
Testing has confirmed this is a NoDB issue. In SQL Server hostname multi-tenant site, this mode permits a user from the root site to log in to a tenant.
I spotted something else in the NoDB test that may be related... in the root site, Role Admin, the number against Administrators was mis-reporting 3 i.e. it was counting the tenant admin user as well as two root site administrators.

**Comment by JimKerslake** [comment]
Extensively tested by use in staging & production site deployments now
