### ISSUE TITLE
ckEditor / content templates 'browse server' opens to wrong tenant location

### ISSUE THREAD

**Issue by JimKerslake** [cloudscribe/cloudscribe#766]
In a folder-name multi-tenant site, the 'browse server' button that opens up a file browse session on the server opens up to an incorrect tenant - the first one used after app is started. 
(this suggests some kind of caching / singleton lifespan)

This is true for the dropzone components in page content templates, and also from the ckEditor image browser in the toolbar.

**Comment by JimKerslake** [comment]
should be resolved - 
re-worked the ckOptions resolver.

**Comment by CrispinF** [comment]
This is working nicely in the LHLP multi-tenant site. @JimKerslake can you confirm what package/version this fix has been released in?

**Comment by JimKerslake** [comment]
@CrispinF   cloudscribe.core.web at 4.1.12
