### ISSUE TITLE
Registration validation feedback is misleading

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#768]
Possibly related to #765 and #719
This image illustrates the problem, with the green ticks appearing for values that are not valid on username and password:
![image](https://user-images.githubusercontent.com/10574730/125911156-b9181adf-4ec3-4d96-91fe-dc8c68d07b17.png)

**Comment by JimKerslake** [comment]
Test plan:  the above bad user registration entries generate appropriate validation fail messages
