### ISSUE TITLE
Update SixLabour.ImageSharp.Web NuGet package references

### ISSUE THREAD

**Issue by MikeFrancisESDM** [cloudscribe/cloudscribe#778]
Currently set to 1.0.0-beta0004, latest stable is 1.0.3
This may be the cause of upload errors we are getting for some images.
Possibly related to : 

https://github.com/SixLabors/ImageSharp/issues/624

**Comment by JimKerslake** [comment]
SixLabors.ImageSharp >> Version="1.0.3"

Then the chain follows:
cloudscribe.FileManager.Web   >> 4.1.1
cloudscribe.FileManager.CoreIntegration  >> 4.1.1
cloudscribe.Core.Web >> 4.1.15

Needs a test that image upload to file manager is still OK.

**Comment by JimKerslake** [comment]
Test plan: Image upload to file manager still works, and the 'rogue' one linked above now uploads without error.
