### ISSUE TITLE
After password reset, signing in should not redirect back to reset confirmation page

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#781]
Forgot password > click link in email > reset password > see confirmation page > sign in > redirected back to /account/resetpasswordconfirmation (confusing!). 
I think there are already exceptions to sign in redirection, and we should add this one.

**Comment by JimKerslake** [comment]
cs.Core.Web at 6.0.5

Test plan:  Follow the "forgot password >> email >> enter new password" workflow.
After passwd is successfully changed, Login to site with new password.
Successful login should route you to site home page.
