### ISSUE TITLE
VS 2022 .NET 6 EF 6

### ISSUE THREAD

**Issue by fasteddys** [cloudscribe/cloudscribe#787]
Hello I am trying to install and run Cloudscribe, its does not full compile, the EF components are giving me errors. Can you please do a full update latest with the nuget package manager and NPM latest and check - in

**Comment by JimKerslake** [comment]
Hi @fasteddys 

At the moment, cloudscribe supports Net5.0 and EF Core5.0.

We do have it on our roadmap to upgrade to 6.0, but it's quite a large job (there are 200+ NuGet packages to manage) - so it's work that we have planned for 2022 but we can't commit to a firm date yet.

The Visual Studio (VSIX) extension that is used to generate an initial cloudscribe solution only works with VS2019 at the moment, and we will also be looking to supply a new one that works in VS2022.

My own experience has been that EF Core is the most tricky aspect of the upgrade to get working.  Trying to reference some Nuget packages that make use of earlier versions of EF Core, from a project that uses the latest EF Core - tends to result in runtime errors... so I have found that I needed to keep consistency in the version of EF Core that is being used, right down through the dependency chain.

So apologies we can't do this for you immediately, but we will certainly be doing it!
