### ISSUE TITLE
A new user registration was attempted - possible glitch with messaging when approval required

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#790]
This functionality was implemented in #686 
We have a scenario where are user gets this:
![image](https://user-images.githubusercontent.com/10574730/153233016-8dad70ab-d71c-430d-b340-71a942c2df0c.png)

Note the final sentence "An administrator still needs to approve...". However that's apparently incorrect in this case - this user's account is already approved, and our contact says it has been for a long time. But the site is indeed configured to _require_ approval. So possibly the logic determining whether or not to display this sentence is incorrect?

**Comment by SimonAnnetts** [comment]
@CrispinF 
I've checked the logic and it looks OK!
In the AccountController the following code is executed if a duplicate user is detected:
```c#
                    bool needsConfirming = CurrentSite.RequireConfirmedEmail && ! existingUser.EmailConfirmed;
                    bool needsApproval = CurrentSite.RequireApprovalBeforeLogin && ! existingUser.AccountApproved;

                    string resetUrl = Url.Action("ForgotPassword", "Account", null, protocol: HttpContext.Request.Scheme);
                    string loginUrl = Url.Action("Login", "Account", null, protocol: HttpContext.Request.Scheme);

                    string confirmUrl = null;

                    if(needsConfirming)
                    {
                        var verifyEmailInfo = await AccountService.GetEmailVerificationInfo(existingUser.Id);
                        confirmUrl = Url.Action(
                            "ConfirmEmail",
                            "Account",
                            new { UserId = existingUser.Id, Code = verifyEmailInfo.EmailVerificationToken },
                            protocol: HttpContext.Request.Scheme
                        );
                    }

                    await EmailSender.SendAccountExistsEmailAsync(
                        CurrentSite,
                        model.Email,
                        StringLocalizer["A new user registration was attempted with your email address"],
                        resetUrl,
                        loginUrl,
                        confirmUrl,
                        needsApproval);
```

Note the logic for needsApproval looks correct - this is passed to the service that generates the email view, which itself contains the following logic:

```c#
@if (@Model.StillNeedsApproval)
{
<p>An administrator still needs to approve the account associated with this email address. Please be patient.</p>    
}
```

**Comment by CrispinF** [comment]
@SimonAnnetts I agree the logic looks correct, so it sounds like our contact was wrong about the precise details of the case. Sadly I never had the details of which user account was affected so couldn't check. But we can test this afresh... here's my attempt on cloudscribe.com using my own account when the site was not configured to require approval:

![image](https://user-images.githubusercontent.com/10574730/218969145-4ecc17b3-48fe-482c-a37c-1e7d1597b76f.png)

and here when the site is set to require approval:

![image](https://user-images.githubusercontent.com/10574730/218969596-e467a4fd-696f-46b0-9aeb-caaa802dc926.png)

That is, I think this passes tests, as we never see the message about an admin still needing to approve.
