### ISSUE TITLE
New Account Pending Approval email to include a link to Manage User page

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#797]
At present the email is like this:
### New User Account Needs Approval 
A new user just registered at mysite.com with email address a@b.com
The account needs to be approved before the new user can login.

It could usefully include a hyperlink to the page on which the account is approved, e.g. 
mysite.com/useradmin/useredit?siteId=26846c6d-e377-402b-bfea-911a0a88a109&userId=53839143-efc7-48a2-b899-71abc382d2ba
with hylperlink text "Manage the new user."

**Comment by SimonAnnetts** [comment]
cloudscribe.Core.CompiledViews.Bootstrap5 version updated to 6.0.16

**Comment by SimonAnnetts** [comment]
Pushed nuget to Nexus for local testing, not yet pushed to nuget.org

**Comment by SimonAnnetts** [comment]
cloudscribe.Core.CompiledViews.Bootstrap5 6.0.16 uploaded to nuget.org
