### ISSUE TITLE
Role Manager - Unable to add user to role

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe#806]
Adding a user to a role no longer works in Bootstrap 5, as multiple modals are not allowed.  When the confirmation dialog appears the underlying modal that contains the form to be submitted gets destroyed.

**Comment by StewartBellamy** [comment]
@JimKerslake and I discussed losing the confirmation modal.

**Comment by JimKerslake** [comment]
@CrispinF @StewartBellamy 
If I'm remembering right, this does still work in the major version of Bootstrap that ships with the cloudscribe v6  template 
(which is BS5.0)

It's only when moving that up manually to the latest BS5.1 that they finally put into practice what they had threatened to do in 5.0 - namely disallowing "stacking" of two modals open at the same time.

Yep agreed that we can just lose the 2nd modal in this case. 
We wondered about any other places where this might be an issue - 
less so in CS itself, but perhaps in our bespoke apps built out on top of it.

**Comment by CrispinF** [comment]
Agree - lose the second modal so we don't hit this problem when we move to 5.1

**Comment by JimKerslake** [comment]
cloudscribe.Core.CompiledViews.Bootstrap5   at v 6.0.7

**Comment by JimKerslake** [comment]
Test Plan:  
Adding user to a role no longer shows a second nested modal.
Add button just adds directly.
