### ISSUE TITLE
Bootstrap5 - Login page

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe#807]
The login page still has some BS4 markup which is causing the input groups not to stretch to size.

![image](https://user-images.githubusercontent.com/10956017/179927672-d494eb88-4d31-4154-abb9-23b7f31bbc96.png)

`<div class="input-group-prepend">` is no longer required

https://getbootstrap.com/docs/5.1/forms/input-group/

The workaround in the meantime is to add:

.input-group-prepend{
    display:flex;
    align-items:stretch;
}

**Comment by CrispinF** [comment]
@JimKerslake would be good to fix this soon as it will affect every project/product, thanks!

**Comment by JimKerslake** [comment]
cloudscribe.Core.CompiledViews.Bootstrap5  version  6.0.2

@StewartBellamy   
remember that CS is using BS5.0  not 5.1 as per your link above.
Makes no difference in this case, but 5.1 brings in other breaking changes.

**Comment by CrispinF** [comment]
Test in a site made with 6.1 template when it's released.
