### ISSUE TITLE
Add users to role paging links

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe#818]
The paging link css classes on the modal to add users to a role is incorrect.  

It should be like:
![image](https://user-images.githubusercontent.com/10956017/180787309-74b33f29-6f27-4d24-bbbb-a434fbe99cab.png)

**Comment by JimKerslake** [comment]
@StewartBellamy  Yes that was presumably always broken.
Try  cloudscribe.Core.CompiledViews.Bootstrap5   now at version 6.0.3.

**Comment by StewartBellamy** [comment]
@JimKerslake - Works a treat, thanks.
