### ISSUE TITLE
Manage User screen needs to be able to disable 2FA

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#823]
At present a user can enable this, but an administrator cannot control it other than in the database cs_User.TwoFactorEnabled
If a user gets locked out, as happened on one of our projects this morning, there's no way in the web interfaces to rescue the user by switching of 2FA for their account.
I think we need to add this to the Manage User screen /useradmin/useredit
But I don't think this wants to be on/off editing, as it should only be switched on by actually enabling a 2FA mechanism themselves. I'm thinking that if the setting is false for the user, simply display this as we do on the User Activity screen:
![image](https://user-images.githubusercontent.com/10574730/185371089-714e9d41-c49a-40b2-836b-c1d9d8cae2dc.png)
But if it is true for the user, also show a button for "Disable 2FA". This will allow the user to log in without 2FA.
(Also noting that if the Site Security Setting "Require users to configure 2 factor authentication" is switched on, the user will be forced to setup 2FA again).

**Comment by JimKerslake** [comment]
Actually the easier way for an admin to rescue a locked-out user would be for them to supply one of the ten Recovery Codes that are stored for each 2FA user, that are designed to enable the user to bypass the 2FA step by using that code instead.  These are 1-time-use codes (after one is used, that is deleted from the db-stored set of ten), so the lock-out scenario could only really occur if the user had already used up their 10 recovery codes.

Once they are safely logged in, the user can either: generate themselves a fresh set of 10, or disable 2FA for themselves.


Anyhow, if the off-switch is still needed: 

As currently implemented in CS, when a user sets up 2FA, they store 2 rows in UserToken table:
AuthenticatorKey
RecoveryCodes

If the user disables their own 2FA, then these rows are not deleted.
So if the user re-enables 2FA, the same authenticator code continues to be used (and following a successful re-registering of the authenticator app code, a fresh set of 10 recovery codes is generated).

So if we make an admin switch as proposed, all that needs to do is toggle the boolean in cs_user table, but leave the above two rows in place.

**Comment by CrispinF** [comment]
@JimKerslake yes we could also add a button for "Send recovery code to user" which sends one by email.
I think the off switch still useful.

**Comment by JimKerslake** [comment]
cloudscribe.Core.Web 6.0.3
cloudscribe.Core.CompiledViews.Bootstrap5  6.0.5

Just an off switch at the moment

**Comment by JimKerslake** [comment]
Test Plan:  
In User management screen there is now a button to disable 2-factor auth for any user for whom it has previously been enabled.
The user can then subsequently login themselves with no 2FA requirement.
They can then re-enable 2FA again, if they want to.
