### ISSUE TITLE
Expiry of authentication cookie should provoke redirect

### ISSUE THREAD

**Issue by JimKerslake** [cloudscribe/cloudscribe#838]
On detection of expiry of the authorisation cookie in the client, the user should be automatically routed to a "you have been logged out" page.  This behaviour should be configurable.

**Comment by CrispinF** [comment]
@JimKerslake here's the behaviour from National Savings:
After 4 minutes...
![image](https://user-images.githubusercontent.com/10574730/194747998-426a1ab4-7199-4e46-a406-77c8c4b739b2.png)

When the countdown reaches zero...
![image](https://user-images.githubusercontent.com/10574730/194748251-fa5ae1ac-4fd4-42ea-a0ad-eeb0659dcbfe.png)

**Comment by CrispinF** [comment]
@JimKerslake as discussed last week, we don't need configurability (initially at least) of when to show the warning, and the polling interval. We do need configurability of the authentication lifespan.

**Comment by JimKerslake** [comment]
@CrispinF  Yes I'm pretty much along these lines.   Main challenge so far - my 'keep alive' button hits a protected endpoint and tries to reauthenticate, which should in theory re-set the cookie... in practice this seems less than fully reliable every time.  With sliding expiry, a cookie should only get refreshed when less than half of its lifespan remaining - but in practice I'm seeing that happen only after time remaining gets down to below about 80-100s, on a 4-minute cookie.  So, you really would not want the warning dialog ever to appear on less than 60 seconds remaining, if the cookie expiry was as short as 4 min.  Secondly, even beyond that, my keep-alive action sometimes (unpredictably) requires two hits to the server before it works, and sometimes just one - reasons unknown.  So will need to poke at that a bit more later.

**Comment by CrispinF** [comment]
Tested:
This after inactivity:
![image](https://user-images.githubusercontent.com/10574730/196032910-4d020886-66a2-4675-af4e-12feb516f21f.png)

"Stay logged in" worked, though took a few seconds (but perhaps because I was working via a VPN).

I would have a slight preference for the modal version, as per National Savings, compared to the inline banner, but this is marginal if there was some reason to do it that way. (?)

This after countdown reaches zero:
![image](https://user-images.githubusercontent.com/10574730/196032926-7f5bc293-c586-4e13-bc46-4cc86f481d94.png)

So all looks good.

Please add strings to default resx that we ship with the template. @JimKerslake

**Comment by JimKerslake** [comment]
strings added to en-US resx file which is the default

**Comment by JimKerslake** [comment]
In sporadic instances I am seeing this launch the countdown, redirect to the "you have been logged out" page, but the user session is still authenticated.

This component currently only responds to its own inference of the time remaining on the auth cookie - and once it has concluded (via a client-side timer) that the cookie will have expired, then it redirects the page.  The component does not pro-actively perform a logout itself.

So possible causes of this issue would be:
client-side JS timer somehow running faster than server-side (or some bug in that countdown timer mechanism with the same effect)
or
some mysterious browser-server interaction during the (apparent) user inactivity period that refreshes the auth cookie behind the scenes (i.e. apparent user 'inactivity' has not really been inactive, if some other ajax thing has hit the server).

I'm considering the more aggressive option of making the timer component actually perform the logout itself - which means that the code would also run through the newly-added option to recalculate the security stamp:
https://github.com/cloudscribe/cloudscribe/issues/940
(Just waiting for a cookie auth timeout will not do that - it needs to be a pro-active logout).

The problem with any alternative approach is that the server query needed to re-check how much time is left on the auth cookie... will refresh the auth cookie.

**Comment by JimKerslake** [comment]
Took ages to see any way around this... I could build a new endpoint for the autologout script to hit - but you want to protect such endpoints with ValidateAntiForgeryToken  - which is why the existing logout is a form with a hidden validation token.   Trouble is, if the auth session has expired, then submitting this form with an invalid token then generates a Bad Request... whereas if it hasn't, this is exactly what you want to do.

Found a strategy for this in the end... the redirected 'You have been timed out' page is the one that can detect the presence of a Logout form still on the page, and submit it if so.

cloudscribe.Web.StaticFiles  to 6.0.10

**Comment by JimKerslake** [comment]
@CrispinF 
Need to consider whether this needs additional work for multi-tenancy.

As currently implemented I think there is just one global value for AppSetting: MaximumInactivityInMinutes 
which will limit the auth cookie lifespan across all tenants.

However the decision whether or not to render the above warning / countdown timer can be on a per-tenant (actually it is on a per-theme) basis, because you can just opt whether to include the necessary partial view into the _Layout file.  Without that, there is no countdown warning... though the auth cookie will expire regardless.
https://www.cloudscribe.com/automated-logout-
