### ISSUE TITLE
Update of registration agreement and requiring users to accept changed agreement - change API behaviour

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe#839]
When the registration agreement is updated there is a checkbox, 'Require Users To Accept Changed Agreement?', which if ticked will force existing users to accept the new agreement before they can do anything else on the website.

For api usage the response redirect to '/account/termsofuse' is not desirable.  Requests that starts with '/api' should, I think, return a 401 unauthorised.

A similar feature was added to stop unauthenticated api users being redirected to the login screen, i.e. they now get a 403 rather redirected to login.

**Comment by StewartBellamy** [comment]
@JimKerslake - Tested on a client api, works a treat.  No more redirects to '/account/termsofuse'  for api calls and continues to work as expected for normal website use.

**Comment by JimKerslake** [comment]
cloudscribe.Core.Web at 6.0.13  should now return a Forbidden 43 - again please do test

**Comment by StewartBellamy** [comment]
@JimKerslake  - tested and 403 working
