### ISSUE TITLE
Email queue filling error log when connection to database is lost

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe#849]
The email queue is swamping the log with thousands of error when the database server get rebooted in the early hours. Latest example is 6500 connection errors logged over a 20 second period.

![image](https://user-images.githubusercontent.com/10956017/196371177-055e13ce-e78c-4aa2-8824-6e06ee8c0580.png)
![image](https://user-images.githubusercontent.com/10956017/196371404-7b55ac4a-49d2-4ce1-bb6a-ebbe324f9813.png)
![image](https://user-images.githubusercontent.com/10956017/196371593-6b74494d-d163-4643-9f4a-945a04ee38f1.png)
![image](https://user-images.githubusercontent.com/10956017/196371794-1e438282-5b13-4bb2-bcf6-60583e651a48.png)

**Comment by JimKerslake** [comment]
cross-ref  https://github.com/exeGesIS-SDM/cloudscribe.Messaging/issues/21
