### ISSUE TITLE
Profile image uploads aren't working

### ISSUE THREAD

**Issue by AlphaComposite** [cloudscribe/cloudscribe#856]
Every image I've tried to add for a profile image isn't working. It's just a blank square. The uploaded image never appears in the image editor. I'm logged in as the admin user if that matters.

**Comment by AlphaComposite** [comment]
There's more to this issue. If you crop the image, the profile image isn't handled properly by the Sixlabors implementation. Some strange pixelation occurs. 

I've attached the original file and the cropped image file for comparison.

![businessman-png-369](https://user-images.githubusercontent.com/25360554/203861240-0f28f40c-6afc-4a7a-8a1d-09ef4e29d5da.png)

![businessman-png-369-crop](https://user-images.githubusercontent.com/25360554/203861302-1f3ad47a-ad47-4cbc-8d0a-6f4997831af3.png)

**Comment by CrispinF** [comment]
@AlphaComposite thanks for reporting this - we'll investigate asap.

**Comment by CrispinF** [comment]
@AlphaComposite I've just tested this in a cloudscribe site and it worked fine.
Also could you clarify your report? Initially you said the selected image never appears in the box... but then you said that cropping the image leads to a corrupted image. But cropping is only possibly after an image has been successfully selected and appears in the box.
Could you possibly provide a very clear set of steps to replicate the problem(s), with screenshots?

**Comment by CrispinF** [comment]
@JimKerslake that doesn't match my observation - I added a large image, and it was resized during upload perfectly.
