### ISSUE TITLE
Failed login does not increment 'AccessFailedCount'

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe#864]
Failed logins, with the correct username/email, do not increment the 'AccessFailedCount'

**Comment by StewartBellamy** [comment]
Fixed in cloudscribe.Core.Web v6.0.18

**Comment by SimonAnnetts** [comment]
Linked to #860

**Comment by JimKerslake** [comment]
From a bit of pragmatic testing on some deployed sites, we need a re-check whether the process of AccessFailedCount exceeding the limit in the Site table does in fact trigger the user to get locked out.  Not seeing it working at present - but maybe we're mis-configured somehow.

**Comment by StewartBellamy** [comment]
@JimKerslake - Check that my code change is still there and hasn't been lost during a branch merge and that the sites are actually running the correct version with the code change in.  No configuring to do, unless there are some site settings?

**Comment by JimKerslake** [comment]
@StewartBellamy  They can log in successfully at this point, even if theoretically still waiting for the current time to pass the LockoutEndDateUtc   - and their AccessFailedCount is back to zero so they can do another 10 failed logins if they like.
I agree I might have expected the account to be disabled to all login attempts for this 5 minute duration... but not seeing that in practice.
What this mechanism does (as it stands) is to interrupt the flow of someone hitting the login button repeatedly (perhaps with an automated tool).

**Comment by JimKerslake** [comment]
@StewartBellamy I have fixed it now so that the account is fully locked against any kind of login for that time duration - stricter behaviour that we would have expected.  Will publish tomorrow.
