### ISSUE TITLE
Two factor auth Enable authenticator screen has dead link for Windows Phone

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#869]
/manage/enableauthenticator
![image](https://user-images.githubusercontent.com/10574730/219891120-eacae611-7a9f-49c9-b855-0fe509c196d2.png)

**Comment by CrispinF** [comment]
Affected view https://github.com/cloudscribe/cloudscribe/blob/50bcdcb7a02eeb1986150294f2ce8876d56fbf7b/src/cloudscribe.Core.CompiledViews.Bootstrap5/Views/Manage/EnableAuthenticator.cshtml

**Comment by SimonAnnetts** [comment]
cloudscribe.Core.CompiledViews.Bootstrap5 @ 6.0.17

**Comment by SimonAnnetts** [comment]
cloudscribe.Core.Web @ 6.0.24
