### ISSUE TITLE
Label is linked to the wrong checkbox in Identity Server Edit API Client view

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#877]
https://github.com/cloudscribe/cloudscribe/blob/c5903c917d492ee4947cccd46c94a21365b02e79/src/cloudscribe.IdentityServerIntegration.CompiledViews.Bootstrap5/Views/Clients/EditClientPartial.cshtml#L115

Should be asp-for="AllowRememberConsent"

**Comment by SimonAnnetts** [comment]
cloudscribe.IdentityServerIntegration.CompiledViews.Bootstrap5 @ 6.0.2
