### ISSUE TITLE
Automatic image resize can lose content of image below top strip

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#892]
This uploaded image original:

![image](https://user-images.githubusercontent.com/10574730/224711929-6b22d36f-5bf5-4a12-a1aa-7f25deb62d8b.png)

was resized automatically to this:

![image](https://user-images.githubusercontent.com/10574730/224712098-505bbb41-c695-49ad-be64-1250dec5e809.png)

Note that the image has the same ratio of dimensions as the original, but has lost its contents.

This has been observed in two different sites. The exact result can differ each time. On one attempt the lower part of the image looked like this:

![image](https://user-images.githubusercontent.com/10574730/224712384-153519a8-c1e4-4949-9697-d6c0dec8ed3b.png)

This has been observed with PNG files from disk, and with images pasted into the CK Editor from the clipboard (via Windows Snip tool) - these seem to be in PNG form.

The resizing is being carried out by SixLabors.ImageSharp

**Comment by CrispinF** [comment]
Suggest we can upgrade from v1.0.3 to v3.0.0 https://www.nuget.org/packages/SixLabors.ImageSharp/ ?

**Comment by SimonAnnetts** [comment]
cloudscribe.FileManager.Web.6.0.3.nupkg
cloudscribe.FileManager.CoreIntegration.6.0.2.nupkg
cloudscribe.Core.Web.6.0.27.nupkg
