### ISSUE TITLE
Pasting a PNG image from clipboard into the upgraded CK Editor can crash

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#893]
This was a CTRL+V after taking a screenshot using the Windows Snipping tool.
Some images work fine, but a larger image (dimension about 1333 wide) resulted in this:

![image](https://user-images.githubusercontent.com/10574730/224715736-2c70950c-fba4-43eb-b68b-81220ef5de23.png)

3/13/2023 1:03:02 PM Error 80.69.7.xxxx cloudscribe.FileManager.Web.Services.FileManagerService /filemanager/dropfile

Bad method for ZLIB header: cmf=133: at SixLabors.ImageSharp.Formats.Png.Zlib.ZlibInflateStream.InitializeInflateStream(Boolean isCriticalChunk) at SixLabors.ImageSharp.Formats.Png.Zlib.ZlibInflateStream.AllocateNewBytes(Int32 bytes, Boolean isCriticalChunk) at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ReadScanlines[TPixel](PngChunk chunk, ImageFrame`1 image, PngMetadata pngMetadata) at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken) at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory) at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream) at SixLabors.ImageSharp.Formats.Png.PngDecoder.Decode[TPixel](Configuration configuration, Stream stream) at SixLabors.ImageSharp.Formats.Png.PngDecoder.Decode(Configuration configuration, Stream stream) at SixLabors.ImageSharp.Image.Decode(Stream stream, Configuration config) at SixLabors.ImageSharp.Image.<>c__DisplayClass137_0.<Load>b__0(Stream s) at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action) at SixLabors.ImageSharp.Image.Load(Configuration configuration, Stream stream, IImageFormat& format) at SixLabors.ImageSharp.Image.Load(Configuration configuration, Stream stream) at SixLabors.ImageSharp.Image.Load(Stream stream) at cloudscribe.FileManager.Web.Services.ImageSharpResizer.ResizeImage(String sourceFilePath, String targetDirectoryPath, String newFileName, String mimeType, Int32 maxWidth, Int32 maxHeight, Boolean allowEnlargement, Int32 quality) at cloudscribe.FileManager.Web.Services.FileManagerService.ProcessFile(IFormFile formFile, ImageProcessingOptions options, Nullable`1 resizeImages, Nullable`1 maxWidth, Nullable`1 maxHeight, String requestedVirtualPath, String newFileName, Boolean allowRootPath, Boolean createThumbnail, Nullable`1 keepOriginal)

The same result when the same image was saved to disk as a PNG, then that file copied and pasted into the editor.

**Comment by SimonAnnetts** [comment]
cloudscribe.FileManager.Web.6.0.3.nupkg
cloudscribe.FileManager.CoreIntegration.6.0.2.nupkg
cloudscribe.Core.Web.6.0.27.nupkg
