### ISSUE TITLE
Improvements to auto-logout

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#913]
Auto-logout implemented under #838 
1. Notification should be modal.
2. If possible, after logout, include redirect parameter on the button that logs you back in again (so that logging in again takes you back to the page you were logged out from.
3. Make this tenant-specific, configured in Security Settings page.

**Comment by JimKerslake** [comment]
Tested working as expected in multi-tenant site which is running in "root admin user can login to tenant sites" mode... the individual tenant's expiry time logs the user out of just that tenant.

**Comment by JimKerslake** [comment]
Works as expected in related sites mode - the setting for the related site Id overrides any other setting in individual tenants.
