### ISSUE TITLE
Query tool API - handle missing parameters as NULL

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#925]
If an API query with a parameter is called without supplying that parameter, no results are returned and an error is logged about the missing SQL parameter.
We can make this more powerful by turning missing parameters into NULL and passing them into the SQL. This allows the underlying SQL to be written in a way that handles missing parameters... e.g. if a filter parameter is not supplied, don't filter on that (whereas atm it just returns nothing and errors silently).

**Comment by SimonAnnetts** [comment]
New nugets:
cloudscribe.QueryTool.Services.6.0.4.nupkg
cloudscribe.QueryTool.Web.6.0.11.nupkg

**Comment by CrispinF** [comment]
Tested ok.
I used a query like this:
select * from "cs_Page" where content like '%' + ISNULL(@searchString,'Andrew Parker') + '%'
then tested with the parameter supplied and not supplied and got the expected results.

**Comment by CrispinF** [comment]
I've updated the documentation to mention this capability. https://www.cloudscribe.com/query-tool
