### ISSUE TITLE
Image upload and resize failure

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#926]
The attached JPG image (see ZIP) fails to re-size when uploaded either in the editor or File Manager, with this in the log:
[IMG_3565.zip](https://github.com/cloudscribe/cloudscribe/files/11424923/IMG_3565.zip)

•	07/05/2023 12:18:39 Error 31.125.19.xxx cloudscribe.FileManager.Web.Services.FileManagerService /xxx/filemanager/upload
Unable to cast object of type 'SixLabors.ImageSharp.Image`1[SixLabors.ImageSharp.PixelFormats.Rgb24]' to type 'SixLabors.ImageSharp.Image`1[SixLabors.ImageSharp.PixelFormats.Rgba32]'.: at cloudscribe.FileManager.Web.Services.ImageSharpResizer.ResizeImage(String sourceFilePath, String targetDirectoryPath, String newFileName, String mimeType, Int32 maxWidth, Int32 maxHeight, Boolean allowEnlargement, Int32 quality)
at cloudscribe.FileManager.Web.Services.FileManagerService.ProcessFile(IFormFile formFile, ImageProcessingOptions options, Nullable`1 resizeImages, Nullable`1 maxWidth, Nullable`1 maxHeight, String requestedVirtualPath, String newFileName, Boolean allowRootPath, Boolean createThumbnail, Nullable`1 keepOriginal)

**Comment by SimonAnnetts** [comment]
@CrispinF this looks related to issue #910  which me and Stew fixed a couple of weeks ago. Have you updated to cloudscribe.Core.Web 6.0.29 ?

**Comment by CrispinF** [comment]
@SimonAnnetts now upgraded, and tested OK. Closing.
