### ISSUE TITLE
Allow user to see own username

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#949]
At present a user cannot see their own username on either /manage or /manage/userinfo
Username can be used to login; indeed it can be the only means to login if the "Allow email for login in addition to username" setting is false. And we have encountered scenarios where cloudscribe user accounts are being used in remote clients that require username instead of email, and we've had users who have forgotten their username and have no way of finding it without help from an Administrator.
(The username property is displayed to administrators in the Manage user page /useradmin/useredit?...)

Is there any reason not to include Username as a read-only property on /manage and /manage/userinfo ?

**Comment by CrispinF** [comment]
@markidox why is the username being pushed to uppercase for this display? 
![Image](https://github.com/user-attachments/assets/875a08f3-a129-42a6-934b-0c06884ca123)

and
![Image](https://github.com/user-attachments/assets/f1cdb218-fa7c-4d0c-ae43-73e0927e5589)

The username here is actually:
![Image](https://github.com/user-attachments/assets/0a1d0e13-6a10-4bbc-8e81-f46420dc157c)

Please display in actual case.

**Comment by markidox** [comment]
@CrispinF This was using the "normalized user name" from the db, which gets pushed in as uppercase, have switched to use the display name which appears to be however the user enters it.

**Comment by CrispinF** [comment]
@markidox no, the display name is something else. We need to see the username. The field is [dbo].[cs_User].[UserName]

**Comment by markidox** [comment]
@CrispinF No worries. That's publishing as we speak.
