### ISSUE TITLE
Paging control cosmetics on Select Roles dialogue when selecting roles to add to an Auth Policy

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe#967]
The pager works but needs a cosmetic fix:

![image](https://github.com/cloudscribe/cloudscribe/assets/10574730/84764d53-6715-44f0-b154-aa5caa90e785)

**Comment by CrispinF** [comment]
@markidox has this been resolved in recent work?

**Comment by markidox** [comment]
@CrispinF Yeah I believe this was the second instance I found where styling had not been applied, it has now.
