### ISSUE TITLE
Store Admin - creating activations

### ISSUE THREAD

**Issue by StewartBellamy** [cloudscribe/cloudscribe#984]
When trying to generate some licenses for localhost I came across a couple of issues.

When creating a new activation the lookup user button that is used to set the hidden userid field doesn't open the modal, this will be a 
BS4/5 data attribute issue.

I overcame this by setting the value in the dom directly.  But creating activations failed for newsletter, forms & surveys and forums.

From the log:

System.InvalidCastException: Cannot write DateTime with Kind=Unspecified to PostgreSQL type 'timestamp with time zone', only UTC is supported.

**Comment by CrispinF** [comment]
@JimKerslake I think this should be in the repo for cloudscribe.com? ... could you take a look?

**Comment by JimKerslake** [comment]
Moved to  https://github.com/GreatHouseBarn/cloudscribe.Commerce/issues/50

**Comment by JimKerslake** [comment]
Manually moved to private repo
