### ISSUE TITLE
2FA QR Code generation, overflow error

### ISSUE THREAD

**Issue by LaineS** [cloudscribe/cloudscribe#996]
When registering as a new using 2FA, an overflow can occur and the QR code image generation fails:

1. Turn on 2FA in Adminstration->Security Settings
2. Register a new user, add your details and get taken to the Two Factor Authentication screen
3. Tap the Add Authenticator' button and the next screen appears with a JS error as below:
Line 52: https://github.com/cloudscribe/cloudscribe/blob/bb4e51f363ad2c4919bac29e76560b0dafbf24f9/src/cloudscribe.Core.CompiledViews.Bootstrap5/Views/Manage/EnableAuthenticator.cshtml

**See example code below**
`new QRCode(document.getElementById("qrCode"),
            {
                text: "otpauth://totp/xxxxx%20National%20Park%20Development%20Syste:xxxxxxxx.xxxxxxxxxxx%2BtestEN@xxxxxxxxxx.com?secret=xxxxxxxxU5H4UMQYKBMDDNMKRNI7EC4V&issuer=xxxxxxxx%20National%20Park%20Development%20Syste&digits=6",
                width: 150,
                height: 150
            });`

![image](https://github.com/cloudscribe/cloudscribe/assets/6085799/513fd70a-be7f-46be-9b32-1077c8820779)

**Comment by JimKerslake** [comment]
I can't see any sign that the third party JS library that is used here to generate the QR code has been updated since it was first incorporated into cloudscribe. 
https://davidshimjs.github.io/qrcodejs/

**Comment by JimKerslake** [comment]
Cloudscribe.Web.StaticFiles at v.6.0.13 (locally published only for the moment)  
implements a proposed fix to the js library (and .min of the same)

Ticket should not be closed until this is rationalised back with the net8 branches.

**Comment by JimKerslake** [comment]
Cloudscribe.Web.StaticFiles at v.6.0.13    updates the qrcode js library
